POST https://buscacepinter.correios.com.br/app/faixa_cep_uf_localidade/carrega-faixa-cep-uf.php
content-type: application/json

{
    "uf": "SC",
    "letraLocalidade": "",
    "ufaux": "",
    "pagina": "/app/faixa_cep_uf_localidade/index.php",
    "cepaux": "",
    "mensagem_alerta": "",
    "localidade": ""
}