export const MIMES = {
    aac: 'audio/aac',
    abw: 'application/x-abiword',
    ai: 'application/postscript',
    arc: 'application/octet-stream',
    avi: 'video/x-msvideo',
    azw: 'application/vnd.amazon.ebook',
    bin: 'application/octet-stream',
    bz: 'application/x-bzip',
    bz2: 'application/x-bzip2',
    csh: 'application/x-csh',
    css: 'text/css',
    csv: 'text/csv',
    doc: 'application/msword',
    dll: 'application/octet-stream',
    eot: 'application/vnd.ms-fontobject',
    epub: 'application/epub+zip',
    gif: 'image/gif',
    htm: 'text/html',
    html: 'text/html',
    ico: 'image/x-icon',
    ics: 'text/calendar',
    jar: 'application/java-archive',
    jpeg: 'image/jpeg',
    jpg: 'image/jpeg',
    js: 'application/javascript',
    json: 'application/json',
    mid: 'audio/midi',
    midi: 'audio/midi',
    mp2: 'audio/mpeg',
    mp3: 'audio/mpeg',
    mp4: 'video/mp4',
    mpa: 'video/mpeg',
    mpe: 'video/mpeg',
    mpeg: 'video/mpeg',
    mpkg: 'application/vnd.apple.installer+xml',
    odp: 'application/vnd.oasis.opendocument.presentation',
    ods: 'application/vnd.oasis.opendocument.spreadsheet',
    odt: 'application/vnd.oasis.opendocument.text',
    oga: 'audio/ogg',
    ogv: 'video/ogg',
    ogx: 'application/ogg',
    otf: 'font/otf',
    png: 'image/png',
    pdf: 'application/pdf',
    ppt: 'application/vnd.ms-powerpoint',
    rar: 'application/x-rar-compressed',
    rtf: 'application/rtf',
    sh: 'application/x-sh',
    svg: 'image/svg+xml',
    swf: 'application/x-shockwave-flash',
    tar: 'application/x-tar',
    tif: 'image/tiff',
    tiff: 'image/tiff',
    ts: 'application/typescript',
    ttf: 'font/ttf',
    txt: 'text/plain',
    vsd: 'application/vnd.visio',
    wav: 'audio/x-wav',
    weba: 'audio/webm',
    webm: 'video/webm',
    webp: 'image/webp',
    woff: 'font/woff',
    woff2: 'font/woff2',
    xhtml: 'application/xhtml+xml',
    xls: 'application/vnd.ms-excel',
    xlsx: 'application/vnd.ms-excel',
    'xlsx_OLD': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    xml: 'application/xml',
    xul: 'application/vnd.mozilla.xul+xml',
    zip: 'application/zip',
    '3gp': 'video/3gpp',
    '3gp_DOES_NOT_CONTAIN_VIDEO': 'audio/3gpp',
    '3gp2': 'video/3gpp2',
    '3gp2_DOES_NOT_CONTAIN_VIDEO': 'audio/3gpp2',
    '7z': 'application/x-7z-compressed'
} as const

export type Mime = keyof typeof MIMES

export const MIMES_NAME: { [x in Mime]: string } = {
    aac: 'Audio File',
    abw: 'Document',
    ai: 'Adobe Illustrator',
    arc: 'Archive',
    avi: 'Video File',
    azw: 'Amazon Kindle',
    bin: 'Binary File',
    bz: 'Bzip Archive',
    bz2: 'Bzip2 Archive',
    csh: 'C Shell Script',
    css: 'Stylesheet',
    csv: 'Comma-Separated Values',
    doc: 'Document',
    dll: 'Dynamic Link Library',
    eot: 'Embedded OpenType',
    epub: 'eBook',
    gif: 'Image',
    htm: 'Web Page',
    html: 'Web Page',
    ico: 'Icon',
    ics: 'Calendar',
    jar: 'Java Archive',
    jpeg: 'Image',
    jpg: 'Image',
    js: 'JavaScript File',
    json: 'JSON File',
    mid: 'MIDI File',
    midi: 'MIDI File',
    mp2: 'MPEG Layer II Audio',
    mp3: 'MP3 Audio',
    mp4: 'MP4 Video',
    mpa: 'MPEG Audio',
    mpe: 'MPEG Video',
    mpeg: 'MPEG Video',
    mpkg: 'Apple Installer Package',
    odp: 'OpenDocument Presentation',
    ods: 'OpenDocument Spreadsheet',
    odt: 'OpenDocument Text',
    oga: 'Ogg Audio',
    ogv: 'Ogg Video',
    ogx: 'Ogg',
    otf: 'OpenType Font',
    png: 'Image',
    pdf: 'PDF Document',
    ppt: 'PowerPoint Presentation',
    rar: 'RAR Archive',
    rtf: 'Rich Text Format',
    sh: 'Shell Script',
    svg: 'Scalable Vector Graphics',
    swf: 'Shockwave Flash',
    tar: 'Tarball Archive',
    tif: 'Image',
    tiff: 'Image',
    ts: 'Transport Stream',
    ttf: 'TrueType Font',
    txt: 'Text File',
    vsd: 'Visio Drawing',
    wav: 'WAV Audio',
    weba: 'Web Audio',
    webm: 'Web Video',
    webp: 'Web Image',
    woff: 'Web Open Font Format',
    woff2: 'Web Open Font Format 2',
    xhtml: 'XHTML Document',
    xls: 'Excel Spreadsheet',
    xlsx: 'Excel Spreadsheet',
    'xlsx_OLD': 'Old Excel Spreadsheet',
    xml: 'XML File',
    xul: 'XUL File',
    zip: 'ZIP Archive',
    '3gp': '3GPP Video',
    '3gp_DOES_NOT_CONTAIN_VIDEO': '3GPP Audio',
    '3gp2': '3GPP2 Video',
    '3gp2_DOES_NOT_CONTAIN_VIDEO': '3GPP2 Audio',
    '7z': '7-Zip Archive',
}

export const MIMES_EXTENSION = Object.keys(MIMES).reduce((acc, mime) => ({ ...acc, [mime]: mime }), {}) as { [x in Mime]: x }
