export const MIMES = {
    '123': 'application/vnd.lotus-1-2-3',
    '1km': 'application/vnd.1000minds.decision-model+xml',
    '3dml': 'text/vnd.in3d.3dml',
    '3ds': 'image/x-3ds',
    '3g2': 'video/3gpp2',
    '3gp': 'video/3gpp',
    '3gpp': 'video/3gpp',
    '3mf': 'model/3mf',
    '7z': 'application/x-7z-compressed',
    'aab': 'application/x-authorware-bin',
    'aac': 'audio/x-aac',
    'aam': 'application/x-authorware-map',
    'aas': 'application/x-authorware-seg',
    'abw': 'application/x-abiword',
    'ac': 'application/vnd.nokia.n-gage.ac+xml',
    'acc': 'application/vnd.americandynamics.acc',
    'ace': 'application/x-ace-compressed',
    'acu': 'application/vnd.acucobol',
    'acutc': 'application/vnd.acucorp',
    'adp': 'audio/adpcm',
    'adts': 'audio/aac',
    'aep': 'application/vnd.audiograph',
    'afm': 'application/x-font-type1',
    'afp': 'application/vnd.ibm.modcap',
    'age': 'application/vnd.age',
    'ahead': 'application/vnd.ahead.space',
    'ai': 'application/postscript',
    'aif': 'audio/x-aiff',
    'aifc': 'audio/x-aiff',
    'aiff': 'audio/x-aiff',
    'air': 'application/vnd.adobe.air-application-installer-package+zip',
    'ait': 'application/vnd.dvb.ait',
    'ami': 'application/vnd.amiga.ami',
    'aml': 'application/automationml-aml+xml',
    'amlx': 'application/automationml-amlx+zip',
    'amr': 'audio/amr',
    'apk': 'application/vnd.android.package-archive',
    'apng': 'image/apng',
    'appcache': 'text/cache-manifest',
    'appinstaller': 'application/appinstaller',
    'application': 'application/x-ms-application',
    'appx': 'application/appx',
    'appxbundle': 'application/appxbundle',
    'apr': 'application/vnd.lotus-approach',
    'arc': 'application/x-freearc',
    'arj': 'application/x-arj',
    'asc': 'application/pgp-signature',
    'asf': 'video/x-ms-asf',
    'asm': 'text/x-asm',
    'aso': 'application/vnd.accpac.simply.aso',
    'asx': 'video/x-ms-asf',
    'atc': 'application/vnd.acucorp',
    'atom': 'application/atom+xml',
    'atomcat': 'application/atomcat+xml',
    'atomdeleted': 'application/atomdeleted+xml',
    'atomsvc': 'application/atomsvc+xml',
    'atx': 'application/vnd.antix.game-component',
    'au': 'audio/basic',
    'avci': 'image/avci',
    'avcs': 'image/avcs',
    'avi': 'video/x-msvideo',
    'avif': 'image/avif',
    'aw': 'application/applixware',
    'azf': 'application/vnd.airzip.filesecure.azf',
    'azs': 'application/vnd.airzip.filesecure.azs',
    'azv': 'image/vnd.airzip.accelerator.azv',
    'azw': 'application/vnd.amazon.ebook',
    'b16': 'image/vnd.pco.b16',
    'bat': 'application/x-msdownload',
    'bcpio': 'application/x-bcpio',
    'bdf': 'application/x-font-bdf',
    'bdm': 'application/vnd.syncml.dm+wbxml',
    'bdoc': 'application/x-bdoc',
    'bed': 'application/vnd.realvnc.bed',
    'bh2': 'application/vnd.fujitsu.oasysprs',
    'bin': 'application/octet-stream',
    'blb': 'application/x-blorb',
    'blorb': 'application/x-blorb',
    'bmi': 'application/vnd.bmi',
    'bmml': 'application/vnd.balsamiq.bmml+xml',
    'bmp': 'image/x-ms-bmp',
    'book': 'application/vnd.framemaker',
    'box': 'application/vnd.previewsystems.box',
    'boz': 'application/x-bzip2',
    'bpk': 'application/octet-stream',
    'bsp': 'model/vnd.valve.source.compiled-map',
    'btf': 'image/prs.btif',
    'btif': 'image/prs.btif',
    'buffer': 'application/octet-stream',
    'bz': 'application/x-bzip',
    'bz2': 'application/x-bzip2',
    'c': 'text/x-c',
    'c11amc': 'application/vnd.cluetrust.cartomobile-config',
    'c11amz': 'application/vnd.cluetrust.cartomobile-config-pkg',
    'c4d': 'application/vnd.clonk.c4group',
    'c4f': 'application/vnd.clonk.c4group',
    'c4g': 'application/vnd.clonk.c4group',
    'c4p': 'application/vnd.clonk.c4group',
    'c4u': 'application/vnd.clonk.c4group',
    'cab': 'application/vnd.ms-cab-compressed',
    'caf': 'audio/x-caf',
    'cap': 'application/vnd.tcpdump.pcap',
    'car': 'application/vnd.curl.car',
    'cat': 'application/vnd.ms-pki.seccat',
    'cb7': 'application/x-cbr',
    'cba': 'application/x-cbr',
    'cbr': 'application/x-cbr',
    'cbt': 'application/x-cbr',
    'cbz': 'application/x-cbr',
    'cc': 'text/x-c',
    'cco': 'application/x-cocoa',
    'cct': 'application/x-director',
    'ccxml': 'application/ccxml+xml',
    'cdbcmsg': 'application/vnd.contact.cmsg',
    'cdf': 'application/x-netcdf',
    'cdfx': 'application/cdfx+xml',
    'cdkey': 'application/vnd.mediastation.cdkey',
    'cdmia': 'application/cdmi-capability',
    'cdmic': 'application/cdmi-container',
    'cdmid': 'application/cdmi-domain',
    'cdmio': 'application/cdmi-object',
    'cdmiq': 'application/cdmi-queue',
    'cdx': 'chemical/x-cdx',
    'cdxml': 'application/vnd.chemdraw+xml',
    'cdy': 'application/vnd.cinderella',
    'cer': 'application/pkix-cert',
    'cfs': 'application/x-cfs-compressed',
    'cgm': 'image/cgm',
    'chat': 'application/x-chat',
    'chm': 'application/vnd.ms-htmlhelp',
    'chrt': 'application/vnd.kde.kchart',
    'cif': 'chemical/x-cif',
    'cii': 'application/vnd.anser-web-certificate-issue-initiation',
    'cil': 'application/vnd.ms-artgalry',
    'cjs': 'application/node',
    'cla': 'application/vnd.claymore',
    'class': 'application/java-vm',
    'cld': 'model/vnd.cld',
    'clkk': 'application/vnd.crick.clicker.keyboard',
    'clkp': 'application/vnd.crick.clicker.palette',
    'clkt': 'application/vnd.crick.clicker.template',
    'clkw': 'application/vnd.crick.clicker.wordbank',
    'clkx': 'application/vnd.crick.clicker',
    'clp': 'application/x-msclip',
    'cmc': 'application/vnd.cosmocaller',
    'cmdf': 'chemical/x-cmdf',
    'cml': 'chemical/x-cml',
    'cmp': 'application/vnd.yellowriver-custom-menu',
    'cmx': 'image/x-cmx',
    'cod': 'application/vnd.rim.cod',
    'coffee': 'text/coffeescript',
    'com': 'application/x-msdownload',
    'conf': 'text/plain',
    'cpio': 'application/x-cpio',
    'cpl': 'application/cpl+xml',
    'cpp': 'text/x-c',
    'cpt': 'application/mac-compactpro',
    'crd': 'application/x-mscardfile',
    'crl': 'application/pkix-crl',
    'crt': 'application/x-x509-ca-cert',
    'crx': 'application/x-chrome-extension',
    'cryptonote': 'application/vnd.rig.cryptonote',
    'csh': 'application/x-csh',
    'csl': 'application/vnd.citationstyles.style+xml',
    'csml': 'chemical/x-csml',
    'csp': 'application/vnd.commonspace',
    'css': 'text/css',
    'cst': 'application/x-director',
    'csv': 'text/csv',
    'cu': 'application/cu-seeme',
    'curl': 'text/vnd.curl',
    'cwl': 'application/cwl',
    'cww': 'application/prs.cww',
    'cxt': 'application/x-director',
    'cxx': 'text/x-c',
    'dae': 'model/vnd.collada+xml',
    'daf': 'application/vnd.mobius.daf',
    'dart': 'application/vnd.dart',
    'dataless': 'application/vnd.fdsn.seed',
    'davmount': 'application/davmount+xml',
    'dbf': 'application/vnd.dbf',
    'dbk': 'application/docbook+xml',
    'dcr': 'application/x-director',
    'dcurl': 'text/vnd.curl.dcurl',
    'dd2': 'application/vnd.oma.dd2+xml',
    'ddd': 'application/vnd.fujixerox.ddd',
    'ddf': 'application/vnd.syncml.dmddf+xml',
    'dds': 'image/vnd.ms-dds',
    'deb': 'application/x-debian-package',
    'def': 'text/plain',
    'deploy': 'application/octet-stream',
    'der': 'application/x-x509-ca-cert',
    'dfac': 'application/vnd.dreamfactory',
    'dgc': 'application/x-dgc-compressed',
    'dib': 'image/bmp',
    'dic': 'text/x-c',
    'dir': 'application/x-director',
    'dis': 'application/vnd.mobius.dis',
    'disposition-notification': 'message/disposition-notification',
    'dist': 'application/octet-stream',
    'distz': 'application/octet-stream',
    'djv': 'image/vnd.djvu',
    'djvu': 'image/vnd.djvu',
    'dll': 'application/x-msdownload',
    'dmg': 'application/x-apple-diskimage',
    'dmp': 'application/vnd.tcpdump.pcap',
    'dms': 'application/octet-stream',
    'dna': 'application/vnd.dna',
    'doc': 'application/msword',
    'docm': 'application/vnd.ms-word.document.macroenabled.12',
    'docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'dot': 'application/msword',
    'dotm': 'application/vnd.ms-word.template.macroenabled.12',
    'dotx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
    'dp': 'application/vnd.osgi.dp',
    'dpg': 'application/vnd.dpgraph',
    'dpx': 'image/dpx',
    'dra': 'audio/vnd.dra',
    'drle': 'image/dicom-rle',
    'dsc': 'text/prs.lines.tag',
    'dssc': 'application/dssc+der',
    'dtb': 'application/x-dtbook+xml',
    'dtd': 'application/xml-dtd',
    'dts': 'audio/vnd.dts',
    'dtshd': 'audio/vnd.dts.hd',
    'dump': 'application/octet-stream',
    'dvb': 'video/vnd.dvb.file',
    'dvi': 'application/x-dvi',
    'dwd': 'application/atsc-dwd+xml',
    'dwf': 'model/vnd.dwf',
    'dwg': 'image/vnd.dwg',
    'dxf': 'image/vnd.dxf',
    'dxp': 'application/vnd.spotfire.dxp',
    'dxr': 'application/x-director',
    'ear': 'application/java-archive',
    'ecelp4800': 'audio/vnd.nuera.ecelp4800',
    'ecelp7470': 'audio/vnd.nuera.ecelp7470',
    'ecelp9600': 'audio/vnd.nuera.ecelp9600',
    'ecma': 'application/ecmascript',
    'edm': 'application/vnd.novadigm.edm',
    'edx': 'application/vnd.novadigm.edx',
    'efif': 'application/vnd.picsel',
    'ei6': 'application/vnd.pg.osasli',
    'elc': 'application/octet-stream',
    'emf': 'image/emf',
    'eml': 'message/rfc822',
    'emma': 'application/emma+xml',
    'emotionml': 'application/emotionml+xml',
    'emz': 'application/x-msmetafile',
    'eol': 'audio/vnd.digital-winds',
    'eot': 'application/vnd.ms-fontobject',
    'eps': 'application/postscript',
    'epub': 'application/epub+zip',
    'es3': 'application/vnd.eszigno3+xml',
    'esa': 'application/vnd.osgi.subsystem',
    'esf': 'application/vnd.epson.esf',
    'et3': 'application/vnd.eszigno3+xml',
    'etx': 'text/x-setext',
    'eva': 'application/x-eva',
    'evy': 'application/x-envoy',
    'exe': 'application/x-msdownload',
    'exi': 'application/exi',
    'exp': 'application/express',
    'exr': 'image/aces',
    'ext': 'application/vnd.novadigm.ext',
    'ez': 'application/andrew-inset',
    'ez2': 'application/vnd.ezpix-album',
    'ez3': 'application/vnd.ezpix-package',
    'f': 'text/x-fortran',
    'f4v': 'video/x-f4v',
    'f77': 'text/x-fortran',
    'f90': 'text/x-fortran',
    'fbs': 'image/vnd.fastbidsheet',
    'fcdt': 'application/vnd.adobe.formscentral.fcdt',
    'fcs': 'application/vnd.isac.fcs',
    'fdf': 'application/vnd.fdf',
    'fdt': 'application/fdt+xml',
    'fe_launch': 'application/vnd.denovo.fcselayout-link',
    'fg5': 'application/vnd.fujitsu.oasysgp',
    'fgd': 'application/x-director',
    'fh': 'image/x-freehand',
    'fh4': 'image/x-freehand',
    'fh5': 'image/x-freehand',
    'fh7': 'image/x-freehand',
    'fhc': 'image/x-freehand',
    'fig': 'application/x-xfig',
    'fits': 'image/fits',
    'flac': 'audio/x-flac',
    'fli': 'video/x-fli',
    'flo': 'application/vnd.micrografx.flo',
    'flv': 'video/x-flv',
    'flw': 'application/vnd.kde.kivio',
    'flx': 'text/vnd.fmi.flexstor',
    'fly': 'text/vnd.fly',
    'fm': 'application/vnd.framemaker',
    'fnc': 'application/vnd.frogans.fnc',
    'fo': 'application/vnd.software602.filler.form+xml',
    'for': 'text/x-fortran',
    'fpx': 'image/vnd.fpx',
    'frame': 'application/vnd.framemaker',
    'fsc': 'application/vnd.fsc.weblaunch',
    'fst': 'image/vnd.fst',
    'ftc': 'application/vnd.fluxtime.clip',
    'fti': 'application/vnd.anser-web-funds-transfer-initiation',
    'fvt': 'video/vnd.fvt',
    'fxp': 'application/vnd.adobe.fxp',
    'fxpl': 'application/vnd.adobe.fxp',
    'fzs': 'application/vnd.fuzzysheet',
    'g2w': 'application/vnd.geoplan',
    'g3': 'image/g3fax',
    'g3w': 'application/vnd.geospace',
    'gac': 'application/vnd.groove-account',
    'gam': 'application/x-tads',
    'gbr': 'application/rpki-ghostbusters',
    'gca': 'application/x-gca-compressed',
    'gdl': 'model/vnd.gdl',
    'gdoc': 'application/vnd.google-apps.document',
    'ged': 'text/vnd.familysearch.gedcom',
    'geo': 'application/vnd.dynageo',
    'geojson': 'application/geo+json',
    'gex': 'application/vnd.geometry-explorer',
    'ggb': 'application/vnd.geogebra.file',
    'ggt': 'application/vnd.geogebra.tool',
    'ghf': 'application/vnd.groove-help',
    'gif': 'image/gif',
    'gim': 'application/vnd.groove-identity-message',
    'glb': 'model/gltf-binary',
    'gltf': 'model/gltf+json',
    'gml': 'application/gml+xml',
    'gmx': 'application/vnd.gmx',
    'gnumeric': 'application/x-gnumeric',
    'gph': 'application/vnd.flographit',
    'gpx': 'application/gpx+xml',
    'gqf': 'application/vnd.grafeq',
    'gqs': 'application/vnd.grafeq',
    'gram': 'application/srgs',
    'gramps': 'application/x-gramps-xml',
    'gre': 'application/vnd.geometry-explorer',
    'grv': 'application/vnd.groove-injector',
    'grxml': 'application/srgs+xml',
    'gsf': 'application/x-font-ghostscript',
    'gsheet': 'application/vnd.google-apps.spreadsheet',
    'gslides': 'application/vnd.google-apps.presentation',
    'gtar': 'application/x-gtar',
    'gtm': 'application/vnd.groove-tool-message',
    'gtw': 'model/vnd.gtw',
    'gv': 'text/vnd.graphviz',
    'gxf': 'application/gxf',
    'gxt': 'application/vnd.geonext',
    'gz': 'application/gzip',
    'h': 'text/x-c',
    'h261': 'video/h261',
    'h263': 'video/h263',
    'h264': 'video/h264',
    'hal': 'application/vnd.hal+xml',
    'hbci': 'application/vnd.hbci',
    'hbs': 'text/x-handlebars-template',
    'hdd': 'application/x-virtualbox-hdd',
    'hdf': 'application/x-hdf',
    'heic': 'image/heic',
    'heics': 'image/heic-sequence',
    'heif': 'image/heif',
    'heifs': 'image/heif-sequence',
    'hej2': 'image/hej2k',
    'held': 'application/atsc-held+xml',
    'hh': 'text/x-c',
    'hjson': 'application/hjson',
    'hlp': 'application/winhlp',
    'hpgl': 'application/vnd.hp-hpgl',
    'hpid': 'application/vnd.hp-hpid',
    'hps': 'application/vnd.hp-hps',
    'hqx': 'application/mac-binhex40',
    'hsj2': 'image/hsj2',
    'htc': 'text/x-component',
    'htke': 'application/vnd.kenameaapp',
    'htm': 'text/html',
    'html': 'text/html',
    'hvd': 'application/vnd.yamaha.hv-dic',
    'hvp': 'application/vnd.yamaha.hv-voice',
    'hvs': 'application/vnd.yamaha.hv-script',
    'i2g': 'application/vnd.intergeo',
    'icc': 'application/vnd.iccprofile',
    'ice': 'x-conference/x-cooltalk',
    'icm': 'application/vnd.iccprofile',
    'ico': 'image/x-icon',
    'ics': 'text/calendar',
    'ief': 'image/ief',
    'ifb': 'text/calendar',
    'ifm': 'application/vnd.shana.informed.formdata',
    'iges': 'model/iges',
    'igl': 'application/vnd.igloader',
    'igm': 'application/vnd.insors.igm',
    'igs': 'model/iges',
    'igx': 'application/vnd.micrografx.igx',
    'iif': 'application/vnd.shana.informed.interchange',
    'img': 'application/octet-stream',
    'imp': 'application/vnd.accpac.simply.imp',
    'ims': 'application/vnd.ms-ims',
    'in': 'text/plain',
    'ini': 'text/plain',
    'ink': 'application/inkml+xml',
    'inkml': 'application/inkml+xml',
    'install': 'application/x-install-instructions',
    'iota': 'application/vnd.astraea-software.iota',
    'ipfix': 'application/ipfix',
    'ipk': 'application/vnd.shana.informed.package',
    'irm': 'application/vnd.ibm.rights-management',
    'irp': 'application/vnd.irepository.package+xml',
    'iso': 'application/x-iso9660-image',
    'itp': 'application/vnd.shana.informed.formtemplate',
    'its': 'application/its+xml',
    'ivp': 'application/vnd.immervision-ivp',
    'ivu': 'application/vnd.immervision-ivu',
    'jad': 'text/vnd.sun.j2me.app-descriptor',
    'jade': 'text/jade',
    'jam': 'application/vnd.jam',
    'jar': 'application/java-archive',
    'jardiff': 'application/x-java-archive-diff',
    'java': 'text/x-java-source',
    'jhc': 'image/jphc',
    'jisp': 'application/vnd.jisp',
    'jls': 'image/jls',
    'jlt': 'application/vnd.hp-jlyt',
    'jng': 'image/x-jng',
    'jnlp': 'application/x-java-jnlp-file',
    'joda': 'application/vnd.joost.joda-archive',
    'jp2': 'image/jp2',
    'jpe': 'image/jpeg',
    'jpeg': 'image/jpeg',
    'jpf': 'image/jpx',
    'jpg': 'image/jpeg',
    'jpg2': 'image/jp2',
    'jpgm': 'video/jpm',
    'jpgv': 'video/jpeg',
    'jph': 'image/jph',
    'jpm': 'video/jpm',
    'jpx': 'image/jpx',
    'js': 'text/javascript',
    'json': 'application/json',
    'json5': 'application/json5',
    'jsonld': 'application/ld+json',
    'jsonml': 'application/jsonml+json',
    'jsx': 'text/jsx',
    'jt': 'model/jt',
    'jxr': 'image/jxr',
    'jxra': 'image/jxra',
    'jxrs': 'image/jxrs',
    'jxs': 'image/jxs',
    'jxsc': 'image/jxsc',
    'jxsi': 'image/jxsi',
    'jxss': 'image/jxss',
    'kar': 'audio/midi',
    'karbon': 'application/vnd.kde.karbon',
    'kdbx': 'application/x-keepass2',
    'key': 'application/x-iwork-keynote-sffkey',
    'kfo': 'application/vnd.kde.kformula',
    'kia': 'application/vnd.kidspiration',
    'kml': 'application/vnd.google-earth.kml+xml',
    'kmz': 'application/vnd.google-earth.kmz',
    'kne': 'application/vnd.kinar',
    'knp': 'application/vnd.kinar',
    'kon': 'application/vnd.kde.kontour',
    'kpr': 'application/vnd.kde.kpresenter',
    'kpt': 'application/vnd.kde.kpresenter',
    'kpxx': 'application/vnd.ds-keypoint',
    'ksp': 'application/vnd.kde.kspread',
    'ktr': 'application/vnd.kahootz',
    'ktx': 'image/ktx',
    'ktx2': 'image/ktx2',
    'ktz': 'application/vnd.kahootz',
    'kwd': 'application/vnd.kde.kword',
    'kwt': 'application/vnd.kde.kword',
    'lasxml': 'application/vnd.las.las+xml',
    'latex': 'application/x-latex',
    'lbd': 'application/vnd.llamagraphics.life-balance.desktop',
    'lbe': 'application/vnd.llamagraphics.life-balance.exchange+xml',
    'les': 'application/vnd.hhe.lesson-player',
    'less': 'text/less',
    'lgr': 'application/lgr+xml',
    'lha': 'application/x-lzh-compressed',
    'link66': 'application/vnd.route66.link66+xml',
    'list': 'text/plain',
    'list3820': 'application/vnd.ibm.modcap',
    'listafp': 'application/vnd.ibm.modcap',
    'litcoffee': 'text/coffeescript',
    'lnk': 'application/x-ms-shortcut',
    'log': 'text/plain',
    'lostxml': 'application/lost+xml',
    'lrf': 'application/octet-stream',
    'lrm': 'application/vnd.ms-lrm',
    'ltf': 'application/vnd.frogans.ltf',
    'lua': 'text/x-lua',
    'luac': 'application/x-lua-bytecode',
    'lvp': 'audio/vnd.lucent.voice',
    'lwp': 'application/vnd.lotus-wordpro',
    'lzh': 'application/x-lzh-compressed',
    'm13': 'application/x-msmediaview',
    'm14': 'application/x-msmediaview',
    'm1v': 'video/mpeg',
    'm21': 'application/mp21',
    'm2a': 'audio/mpeg',
    'm2v': 'video/mpeg',
    'm3a': 'audio/mpeg',
    'm3u': 'audio/x-mpegurl',
    'm3u8': 'application/vnd.apple.mpegurl',
    'm4a': 'audio/x-m4a',
    'm4p': 'application/mp4',
    'm4s': 'video/iso.segment',
    'm4u': 'video/vnd.mpegurl',
    'm4v': 'video/x-m4v',
    'ma': 'application/mathematica',
    'mads': 'application/mads+xml',
    'maei': 'application/mmt-aei+xml',
    'mag': 'application/vnd.ecowin.chart',
    'maker': 'application/vnd.framemaker',
    'man': 'text/troff',
    'manifest': 'text/cache-manifest',
    'map': 'application/json',
    'mar': 'application/octet-stream',
    'markdown': 'text/markdown',
    'mathml': 'application/mathml+xml',
    'mb': 'application/mathematica',
    'mbk': 'application/vnd.mobius.mbk',
    'mbox': 'application/mbox',
    'mc1': 'application/vnd.medcalcdata',
    'mcd': 'application/vnd.mcd',
    'mcurl': 'text/vnd.curl.mcurl',
    'md': 'text/markdown',
    'mdb': 'application/x-msaccess',
    'mdi': 'image/vnd.ms-modi',
    'mdx': 'text/mdx',
    'me': 'text/troff',
    'mesh': 'model/mesh',
    'meta4': 'application/metalink4+xml',
    'metalink': 'application/metalink+xml',
    'mets': 'application/mets+xml',
    'mfm': 'application/vnd.mfmp',
    'mft': 'application/rpki-manifest',
    'mgp': 'application/vnd.osgeo.mapguide.package',
    'mgz': 'application/vnd.proteus.magazine',
    'mid': 'audio/midi',
    'midi': 'audio/midi',
    'mie': 'application/x-mie',
    'mif': 'application/vnd.mif',
    'mime': 'message/rfc822',
    'mj2': 'video/mj2',
    'mjp2': 'video/mj2',
    'mjs': 'text/javascript',
    'mk3d': 'video/x-matroska',
    'mka': 'audio/x-matroska',
    'mkd': 'text/x-markdown',
    'mks': 'video/x-matroska',
    'mkv': 'video/x-matroska',
    'mlp': 'application/vnd.dolby.mlp',
    'mmd': 'application/vnd.chipnuts.karaoke-mmd',
    'mmf': 'application/vnd.smaf',
    'mml': 'text/mathml',
    'mmr': 'image/vnd.fujixerox.edmics-mmr',
    'mng': 'video/x-mng',
    'mny': 'application/x-msmoney',
    'mobi': 'application/x-mobipocket-ebook',
    'mods': 'application/mods+xml',
    'mov': 'video/quicktime',
    'movie': 'video/x-sgi-movie',
    'mp2': 'audio/mpeg',
    'mp21': 'application/mp21',
    'mp2a': 'audio/mpeg',
    'mp3': 'audio/mpeg',
    'mp4': 'video/mp4',
    'mp4a': 'audio/mp4',
    'mp4s': 'application/mp4',
    'mp4v': 'video/mp4',
    'mpc': 'application/vnd.mophun.certificate',
    'mpd': 'application/dash+xml',
    'mpe': 'video/mpeg',
    'mpeg': 'video/mpeg',
    'mpf': 'application/media-policy-dataset+xml',
    'mpg': 'video/mpeg',
    'mpg4': 'video/mp4',
    'mpga': 'audio/mpeg',
    'mpkg': 'application/vnd.apple.installer+xml',
    'mpm': 'application/vnd.blueice.multipass',
    'mpn': 'application/vnd.mophun.application',
    'mpp': 'application/vnd.ms-project',
    'mpt': 'application/vnd.ms-project',
    'mpy': 'application/vnd.ibm.minipay',
    'mqy': 'application/vnd.mobius.mqy',
    'mrc': 'application/marc',
    'mrcx': 'application/marcxml+xml',
    'ms': 'text/troff',
    'mscml': 'application/mediaservercontrol+xml',
    'mseed': 'application/vnd.fdsn.mseed',
    'mseq': 'application/vnd.mseq',
    'msf': 'application/vnd.epson.msf',
    'msg': 'application/vnd.ms-outlook',
    'msh': 'model/mesh',
    'msi': 'application/x-msdownload',
    'msix': 'application/msix',
    'msixbundle': 'application/msixbundle',
    'msl': 'application/vnd.mobius.msl',
    'msm': 'application/octet-stream',
    'msp': 'application/octet-stream',
    'msty': 'application/vnd.muvee.style',
    'mtl': 'model/mtl',
    'mts': 'model/vnd.mts',
    'mus': 'application/vnd.musician',
    'musd': 'application/mmt-usd+xml',
    'musicxml': 'application/vnd.recordare.musicxml+xml',
    'mvb': 'application/x-msmediaview',
    'mvt': 'application/vnd.mapbox-vector-tile',
    'mwf': 'application/vnd.mfer',
    'mxf': 'application/mxf',
    'mxl': 'application/vnd.recordare.musicxml',
    'mxmf': 'audio/mobile-xmf',
    'mxml': 'application/xv+xml',
    'mxs': 'application/vnd.triscape.mxs',
    'mxu': 'video/vnd.mpegurl',
    'n-gage': 'application/vnd.nokia.n-gage.symbian.install',
    'n3': 'text/n3',
    'nb': 'application/mathematica',
    'nbp': 'application/vnd.wolfram.player',
    'nc': 'application/x-netcdf',
    'ncx': 'application/x-dtbncx+xml',
    'nfo': 'text/x-nfo',
    'ngdat': 'application/vnd.nokia.n-gage.data',
    'nitf': 'application/vnd.nitf',
    'nlu': 'application/vnd.neurolanguage.nlu',
    'nml': 'application/vnd.enliven',
    'nnd': 'application/vnd.noblenet-directory',
    'nns': 'application/vnd.noblenet-sealer',
    'nnw': 'application/vnd.noblenet-web',
    'npx': 'image/vnd.net-fpx',
    'nq': 'application/n-quads',
    'nsc': 'application/x-conference',
    'nsf': 'application/vnd.lotus-notes',
    'nt': 'application/n-triples',
    'ntf': 'application/vnd.nitf',
    'numbers': 'application/x-iwork-numbers-sffnumbers',
    'nzb': 'application/x-nzb',
    'oa2': 'application/vnd.fujitsu.oasys2',
    'oa3': 'application/vnd.fujitsu.oasys3',
    'oas': 'application/vnd.fujitsu.oasys',
    'obd': 'application/x-msbinder',
    'obgx': 'application/vnd.openblox.game+xml',
    'obj': 'model/obj',
    'oda': 'application/oda',
    'odb': 'application/vnd.oasis.opendocument.database',
    'odc': 'application/vnd.oasis.opendocument.chart',
    'odf': 'application/vnd.oasis.opendocument.formula',
    'odft': 'application/vnd.oasis.opendocument.formula-template',
    'odg': 'application/vnd.oasis.opendocument.graphics',
    'odi': 'application/vnd.oasis.opendocument.image',
    'odm': 'application/vnd.oasis.opendocument.text-master',
    'odp': 'application/vnd.oasis.opendocument.presentation',
    'ods': 'application/vnd.oasis.opendocument.spreadsheet',
    'odt': 'application/vnd.oasis.opendocument.text',
    'oga': 'audio/ogg',
    'ogex': 'model/vnd.opengex',
    'ogg': 'audio/ogg',
    'ogv': 'video/ogg',
    'ogx': 'application/ogg',
    'omdoc': 'application/omdoc+xml',
    'onepkg': 'application/onenote',
    'onetmp': 'application/onenote',
    'onetoc': 'application/onenote',
    'onetoc2': 'application/onenote',
    'opf': 'application/oebps-package+xml',
    'opml': 'text/x-opml',
    'oprc': 'application/vnd.palm',
    'opus': 'audio/ogg',
    'org': 'text/x-org',
    'osf': 'application/vnd.yamaha.openscoreformat',
    'osfpvg': 'application/vnd.yamaha.openscoreformat.osfpvg+xml',
    'osm': 'application/vnd.openstreetmap.data+xml',
    'otc': 'application/vnd.oasis.opendocument.chart-template',
    'otf': 'font/otf',
    'otg': 'application/vnd.oasis.opendocument.graphics-template',
    'oth': 'application/vnd.oasis.opendocument.text-web',
    'oti': 'application/vnd.oasis.opendocument.image-template',
    'otp': 'application/vnd.oasis.opendocument.presentation-template',
    'ots': 'application/vnd.oasis.opendocument.spreadsheet-template',
    'ott': 'application/vnd.oasis.opendocument.text-template',
    'ova': 'application/x-virtualbox-ova',
    'ovf': 'application/x-virtualbox-ovf',
    'owl': 'application/rdf+xml',
    'oxps': 'application/oxps',
    'oxt': 'application/vnd.openofficeorg.extension',
    'p': 'text/x-pascal',
    'p10': 'application/pkcs10',
    'p12': 'application/x-pkcs12',
    'p7b': 'application/x-pkcs7-certificates',
    'p7c': 'application/pkcs7-mime',
    'p7m': 'application/pkcs7-mime',
    'p7r': 'application/x-pkcs7-certreqresp',
    'p7s': 'application/pkcs7-signature',
    'p8': 'application/pkcs8',
    'pac': 'application/x-ns-proxy-autoconfig',
    'pages': 'application/x-iwork-pages-sffpages',
    'pas': 'text/x-pascal',
    'paw': 'application/vnd.pawaafile',
    'pbd': 'application/vnd.powerbuilder6',
    'pbm': 'image/x-portable-bitmap',
    'pcap': 'application/vnd.tcpdump.pcap',
    'pcf': 'application/x-font-pcf',
    'pcl': 'application/vnd.hp-pcl',
    'pclxl': 'application/vnd.hp-pclxl',
    'pct': 'image/x-pict',
    'pcurl': 'application/vnd.curl.pcurl',
    'pcx': 'image/x-pcx',
    'pdb': 'application/x-pilot',
    'pde': 'text/x-processing',
    'pdf': 'application/pdf',
    'pem': 'application/x-x509-ca-cert',
    'pfa': 'application/x-font-type1',
    'pfb': 'application/x-font-type1',
    'pfm': 'application/x-font-type1',
    'pfr': 'application/font-tdpfr',
    'pfx': 'application/x-pkcs12',
    'pgm': 'image/x-portable-graymap',
    'pgn': 'application/x-chess-pgn',
    'pgp': 'application/pgp-encrypted',
    'php': 'application/x-httpd-php',
    'pic': 'image/x-pict',
    'pkg': 'application/octet-stream',
    'pki': 'application/pkixcmp',
    'pkipath': 'application/pkix-pkipath',
    'pkpass': 'application/vnd.apple.pkpass',
    'pl': 'application/x-perl',
    'plb': 'application/vnd.3gpp.pic-bw-large',
    'plc': 'application/vnd.mobius.plc',
    'plf': 'application/vnd.pocketlearn',
    'pls': 'application/pls+xml',
    'pm': 'application/x-perl',
    'pml': 'application/vnd.ctc-posml',
    'png': 'image/png',
    'pnm': 'image/x-portable-anymap',
    'portpkg': 'application/vnd.macports.portpkg',
    'pot': 'application/vnd.ms-powerpoint',
    'potm': 'application/vnd.ms-powerpoint.template.macroenabled.12',
    'potx': 'application/vnd.openxmlformats-officedocument.presentationml.template',
    'ppam': 'application/vnd.ms-powerpoint.addin.macroenabled.12',
    'ppd': 'application/vnd.cups-ppd',
    'ppm': 'image/x-portable-pixmap',
    'pps': 'application/vnd.ms-powerpoint',
    'ppsm': 'application/vnd.ms-powerpoint.slideshow.macroenabled.12',
    'ppsx': 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
    'ppt': 'application/vnd.ms-powerpoint',
    'pptm': 'application/vnd.ms-powerpoint.presentation.macroenabled.12',
    'pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'pqa': 'application/vnd.palm',
    'prc': 'model/prc',
    'pre': 'application/vnd.lotus-freelance',
    'prf': 'application/pics-rules',
    'provx': 'application/provenance+xml',
    'ps': 'application/postscript',
    'psb': 'application/vnd.3gpp.pic-bw-small',
    'psd': 'image/vnd.adobe.photoshop',
    'psf': 'application/x-font-linux-psf',
    'pskcxml': 'application/pskc+xml',
    'pti': 'image/prs.pti',
    'ptid': 'application/vnd.pvi.ptid1',
    'pub': 'application/x-mspublisher',
    'pvb': 'application/vnd.3gpp.pic-bw-var',
    'pwn': 'application/vnd.3m.post-it-notes',
    'pya': 'audio/vnd.ms-playready.media.pya',
    'pyo': 'model/vnd.pytha.pyox',
    'pyox': 'model/vnd.pytha.pyox',
    'pyv': 'video/vnd.ms-playready.media.pyv',
    'qam': 'application/vnd.epson.quickanime',
    'qbo': 'application/vnd.intu.qbo',
    'qfx': 'application/vnd.intu.qfx',
    'qps': 'application/vnd.publishare-delta-tree',
    'qt': 'video/quicktime',
    'qwd': 'application/vnd.quark.quarkxpress',
    'qwt': 'application/vnd.quark.quarkxpress',
    'qxb': 'application/vnd.quark.quarkxpress',
    'qxd': 'application/vnd.quark.quarkxpress',
    'qxl': 'application/vnd.quark.quarkxpress',
    'qxt': 'application/vnd.quark.quarkxpress',
    'ra': 'audio/x-realaudio',
    'ram': 'audio/x-pn-realaudio',
    'raml': 'application/raml+yaml',
    'rapd': 'application/route-apd+xml',
    'rar': 'application/x-rar-compressed',
    'ras': 'image/x-cmu-raster',
    'rcprofile': 'application/vnd.ipunplugged.rcprofile',
    'rdf': 'application/rdf+xml',
    'rdz': 'application/vnd.data-vision.rdz',
    'relo': 'application/p2p-overlay+xml',
    'rep': 'application/vnd.businessobjects',
    'res': 'application/x-dtbresource+xml',
    'rgb': 'image/x-rgb',
    'rif': 'application/reginfo+xml',
    'rip': 'audio/vnd.rip',
    'ris': 'application/x-research-info-systems',
    'rl': 'application/resource-lists+xml',
    'rlc': 'image/vnd.fujixerox.edmics-rlc',
    'rld': 'application/resource-lists-diff+xml',
    'rm': 'application/vnd.rn-realmedia',
    'rmi': 'audio/midi',
    'rmp': 'audio/x-pn-realaudio-plugin',
    'rms': 'application/vnd.jcp.javame.midlet-rms',
    'rmvb': 'application/vnd.rn-realmedia-vbr',
    'rnc': 'application/relax-ng-compact-syntax',
    'rng': 'application/xml',
    'roa': 'application/rpki-roa',
    'roff': 'text/troff',
    'rp9': 'application/vnd.cloanto.rp9',
    'rpm': 'application/x-redhat-package-manager',
    'rpss': 'application/vnd.nokia.radio-presets',
    'rpst': 'application/vnd.nokia.radio-preset',
    'rq': 'application/sparql-query',
    'rs': 'application/rls-services+xml',
    'rsat': 'application/atsc-rsat+xml',
    'rsd': 'application/rsd+xml',
    'rsheet': 'application/urc-ressheet+xml',
    'rss': 'application/rss+xml',
    'rtf': 'text/rtf',
    'rtx': 'text/richtext',
    'run': 'application/x-makeself',
    'rusd': 'application/route-usd+xml',
    's': 'text/x-asm',
    's3m': 'audio/s3m',
    'saf': 'application/vnd.yamaha.smaf-audio',
    'sass': 'text/x-sass',
    'sbml': 'application/sbml+xml',
    'sc': 'application/vnd.ibm.secure-container',
    'scd': 'application/x-msschedule',
    'scm': 'application/vnd.lotus-screencam',
    'scq': 'application/scvp-cv-request',
    'scs': 'application/scvp-cv-response',
    'scss': 'text/x-scss',
    'scurl': 'text/vnd.curl.scurl',
    'sda': 'application/vnd.stardivision.draw',
    'sdc': 'application/vnd.stardivision.calc',
    'sdd': 'application/vnd.stardivision.impress',
    'sdkd': 'application/vnd.solent.sdkm+xml',
    'sdkm': 'application/vnd.solent.sdkm+xml',
    'sdp': 'application/sdp',
    'sdw': 'application/vnd.stardivision.writer',
    'sea': 'application/x-sea',
    'see': 'application/vnd.seemail',
    'seed': 'application/vnd.fdsn.seed',
    'sema': 'application/vnd.sema',
    'semd': 'application/vnd.semd',
    'semf': 'application/vnd.semf',
    'senmlx': 'application/senml+xml',
    'sensmlx': 'application/sensml+xml',
    'ser': 'application/java-serialized-object',
    'setpay': 'application/set-payment-initiation',
    'setreg': 'application/set-registration-initiation',
    'sfd-hdstx': 'application/vnd.hydrostatix.sof-data',
    'sfs': 'application/vnd.spotfire.sfs',
    'sfv': 'text/x-sfv',
    'sgi': 'image/sgi',
    'sgl': 'application/vnd.stardivision.writer-global',
    'sgm': 'text/sgml',
    'sgml': 'text/sgml',
    'sh': 'application/x-sh',
    'shar': 'application/x-shar',
    'shex': 'text/shex',
    'shf': 'application/shf+xml',
    'shtml': 'text/html',
    'sid': 'image/x-mrsid-image',
    'sieve': 'application/sieve',
    'sig': 'application/pgp-signature',
    'sil': 'audio/silk',
    'silo': 'model/mesh',
    'sis': 'application/vnd.symbian.install',
    'sisx': 'application/vnd.symbian.install',
    'sit': 'application/x-stuffit',
    'sitx': 'application/x-stuffitx',
    'siv': 'application/sieve',
    'skd': 'application/vnd.koan',
    'skm': 'application/vnd.koan',
    'skp': 'application/vnd.koan',
    'skt': 'application/vnd.koan',
    'sldm': 'application/vnd.ms-powerpoint.slide.macroenabled.12',
    'sldx': 'application/vnd.openxmlformats-officedocument.presentationml.slide',
    'slim': 'text/slim',
    'slm': 'text/slim',
    'sls': 'application/route-s-tsid+xml',
    'slt': 'application/vnd.epson.salt',
    'sm': 'application/vnd.stepmania.stepchart',
    'smf': 'application/vnd.stardivision.math',
    'smi': 'application/smil+xml',
    'smil': 'application/smil+xml',
    'smv': 'video/x-smv',
    'smzip': 'application/vnd.stepmania.package',
    'snd': 'audio/basic',
    'snf': 'application/x-font-snf',
    'so': 'application/octet-stream',
    'spc': 'application/x-pkcs7-certificates',
    'spdx': 'text/spdx',
    'spf': 'application/vnd.yamaha.smaf-phrase',
    'spl': 'application/x-futuresplash',
    'spot': 'text/vnd.in3d.spot',
    'spp': 'application/scvp-vp-response',
    'spq': 'application/scvp-vp-request',
    'spx': 'audio/ogg',
    'sql': 'application/x-sql',
    'src': 'application/x-wais-source',
    'srt': 'application/x-subrip',
    'sru': 'application/sru+xml',
    'srx': 'application/sparql-results+xml',
    'ssdl': 'application/ssdl+xml',
    'sse': 'application/vnd.kodak-descriptor',
    'ssf': 'application/vnd.epson.ssf',
    'ssml': 'application/ssml+xml',
    'st': 'application/vnd.sailingtracker.track',
    'stc': 'application/vnd.sun.xml.calc.template',
    'std': 'application/vnd.sun.xml.draw.template',
    'stf': 'application/vnd.wt.stf',
    'sti': 'application/vnd.sun.xml.impress.template',
    'stk': 'application/hyperstudio',
    'stl': 'model/stl',
    'stpx': 'model/step+xml',
    'stpxz': 'model/step-xml+zip',
    'stpz': 'model/step+zip',
    'str': 'application/vnd.pg.format',
    'stw': 'application/vnd.sun.xml.writer.template',
    'styl': 'text/stylus',
    'stylus': 'text/stylus',
    'sub': 'text/vnd.dvb.subtitle',
    'sus': 'application/vnd.sus-calendar',
    'susp': 'application/vnd.sus-calendar',
    'sv4cpio': 'application/x-sv4cpio',
    'sv4crc': 'application/x-sv4crc',
    'svc': 'application/vnd.dvb.service',
    'svd': 'application/vnd.svd',
    'svg': 'image/svg+xml',
    'svgz': 'image/svg+xml',
    'swa': 'application/x-director',
    'swf': 'application/x-shockwave-flash',
    'swi': 'application/vnd.aristanetworks.swi',
    'swidtag': 'application/swid+xml',
    'sxc': 'application/vnd.sun.xml.calc',
    'sxd': 'application/vnd.sun.xml.draw',
    'sxg': 'application/vnd.sun.xml.writer.global',
    'sxi': 'application/vnd.sun.xml.impress',
    'sxm': 'application/vnd.sun.xml.math',
    'sxw': 'application/vnd.sun.xml.writer',
    't': 'text/troff',
    't3': 'application/x-t3vm-image',
    't38': 'image/t38',
    'taglet': 'application/vnd.mynfc',
    'tao': 'application/vnd.tao.intent-module-archive',
    'tap': 'image/vnd.tencent.tap',
    'tar': 'application/x-tar',
    'tcap': 'application/vnd.3gpp2.tcap',
    'tcl': 'application/x-tcl',
    'td': 'application/urc-targetdesc+xml',
    'teacher': 'application/vnd.smart.teacher',
    'tei': 'application/tei+xml',
    'teicorpus': 'application/tei+xml',
    'tex': 'application/x-tex',
    'texi': 'application/x-texinfo',
    'texinfo': 'application/x-texinfo',
    'text': 'text/plain',
    'tfi': 'application/thraud+xml',
    'tfm': 'application/x-tex-tfm',
    'tfx': 'image/tiff-fx',
    'tga': 'image/x-tga',
    'thmx': 'application/vnd.ms-officetheme',
    'tif': 'image/tiff',
    'tiff': 'image/tiff',
    'tk': 'application/x-tcl',
    'tmo': 'application/vnd.tmobile-livetv',
    'toml': 'application/toml',
    'torrent': 'application/x-bittorrent',
    'tpl': 'application/vnd.groove-tool-template',
    'tpt': 'application/vnd.trid.tpt',
    'tr': 'text/troff',
    'tra': 'application/vnd.trueapp',
    'trig': 'application/trig',
    'trm': 'application/x-msterminal',
    'ts': 'video/mp2t',
    'tsd': 'application/timestamped-data',
    'tsv': 'text/tab-separated-values',
    'ttc': 'font/collection',
    'ttf': 'font/ttf',
    'ttl': 'text/turtle',
    'ttml': 'application/ttml+xml',
    'twd': 'application/vnd.simtech-mindmapper',
    'twds': 'application/vnd.simtech-mindmapper',
    'txd': 'application/vnd.genomatix.tuxedo',
    'txf': 'application/vnd.mobius.txf',
    'txt': 'text/plain',
    'u32': 'application/x-authorware-bin',
    'u3d': 'model/u3d',
    'u8dsn': 'message/global-delivery-status',
    'u8hdr': 'message/global-headers',
    'u8mdn': 'message/global-disposition-notification',
    'u8msg': 'message/global',
    'ubj': 'application/ubjson',
    'udeb': 'application/x-debian-package',
    'ufd': 'application/vnd.ufdl',
    'ufdl': 'application/vnd.ufdl',
    'ulx': 'application/x-glulx',
    'umj': 'application/vnd.umajin',
    'unityweb': 'application/vnd.unity',
    'uo': 'application/vnd.uoml+xml',
    'uoml': 'application/vnd.uoml+xml',
    'uri': 'text/uri-list',
    'uris': 'text/uri-list',
    'urls': 'text/uri-list',
    'usda': 'model/vnd.usda',
    'usdz': 'model/vnd.usdz+zip',
    'ustar': 'application/x-ustar',
    'utz': 'application/vnd.uiq.theme',
    'uu': 'text/x-uuencode',
    'uva': 'audio/vnd.dece.audio',
    'uvd': 'application/vnd.dece.data',
    'uvf': 'application/vnd.dece.data',
    'uvg': 'image/vnd.dece.graphic',
    'uvh': 'video/vnd.dece.hd',
    'uvi': 'image/vnd.dece.graphic',
    'uvm': 'video/vnd.dece.mobile',
    'uvp': 'video/vnd.dece.pd',
    'uvs': 'video/vnd.dece.sd',
    'uvt': 'application/vnd.dece.ttml+xml',
    'uvu': 'video/vnd.uvvu.mp4',
    'uvv': 'video/vnd.dece.video',
    'uvva': 'audio/vnd.dece.audio',
    'uvvd': 'application/vnd.dece.data',
    'uvvf': 'application/vnd.dece.data',
    'uvvg': 'image/vnd.dece.graphic',
    'uvvh': 'video/vnd.dece.hd',
    'uvvi': 'image/vnd.dece.graphic',
    'uvvm': 'video/vnd.dece.mobile',
    'uvvp': 'video/vnd.dece.pd',
    'uvvs': 'video/vnd.dece.sd',
    'uvvt': 'application/vnd.dece.ttml+xml',
    'uvvu': 'video/vnd.uvvu.mp4',
    'uvvv': 'video/vnd.dece.video',
    'uvvx': 'application/vnd.dece.unspecified',
    'uvvz': 'application/vnd.dece.zip',
    'uvx': 'application/vnd.dece.unspecified',
    'uvz': 'application/vnd.dece.zip',
    'vbox': 'application/x-virtualbox-vbox',
    'vbox-extpack': 'application/x-virtualbox-vbox-extpack',
    'vcard': 'text/vcard',
    'vcd': 'application/x-cdlink',
    'vcf': 'text/x-vcard',
    'vcg': 'application/vnd.groove-vcard',
    'vcs': 'text/x-vcalendar',
    'vcx': 'application/vnd.vcx',
    'vdi': 'application/x-virtualbox-vdi',
    'vds': 'model/vnd.sap.vds',
    'vhd': 'application/x-virtualbox-vhd',
    'vis': 'application/vnd.visionary',
    'viv': 'video/vnd.vivo',
    'vmdk': 'application/x-virtualbox-vmdk',
    'vob': 'video/x-ms-vob',
    'vor': 'application/vnd.stardivision.writer',
    'vox': 'application/x-authorware-bin',
    'vrml': 'model/vrml',
    'vsd': 'application/vnd.visio',
    'vsf': 'application/vnd.vsf',
    'vss': 'application/vnd.visio',
    'vst': 'application/vnd.visio',
    'vsw': 'application/vnd.visio',
    'vtf': 'image/vnd.valve.source.texture',
    'vtt': 'text/vtt',
    'vtu': 'model/vnd.vtu',
    'vxml': 'application/voicexml+xml',
    'w3d': 'application/x-director',
    'wad': 'application/x-doom',
    'wadl': 'application/vnd.sun.wadl+xml',
    'war': 'application/java-archive',
    'wasm': 'application/wasm',
    'wav': 'audio/x-wav',
    'wax': 'audio/x-ms-wax',
    'wbmp': 'image/vnd.wap.wbmp',
    'wbs': 'application/vnd.criticaltools.wbs+xml',
    'wbxml': 'application/vnd.wap.wbxml',
    'wcm': 'application/vnd.ms-works',
    'wdb': 'application/vnd.ms-works',
    'wdp': 'image/vnd.ms-photo',
    'weba': 'audio/webm',
    'webapp': 'application/x-web-app-manifest+json',
    'webm': 'video/webm',
    'webmanifest': 'application/manifest+json',
    'webp': 'image/webp',
    'wg': 'application/vnd.pmi.widget',
    'wgsl': 'text/wgsl',
    'wgt': 'application/widget',
    'wif': 'application/watcherinfo+xml',
    'wks': 'application/vnd.ms-works',
    'wm': 'video/x-ms-wm',
    'wma': 'audio/x-ms-wma',
    'wmd': 'application/x-ms-wmd',
    'wmf': 'image/wmf',
    'wml': 'text/vnd.wap.wml',
    'wmlc': 'application/vnd.wap.wmlc',
    'wmls': 'text/vnd.wap.wmlscript',
    'wmlsc': 'application/vnd.wap.wmlscriptc',
    'wmv': 'video/x-ms-wmv',
    'wmx': 'video/x-ms-wmx',
    'wmz': 'application/x-msmetafile',
    'woff': 'font/woff',
    'woff2': 'font/woff2',
    'wpd': 'application/vnd.wordperfect',
    'wpl': 'application/vnd.ms-wpl',
    'wps': 'application/vnd.ms-works',
    'wqd': 'application/vnd.wqd',
    'wri': 'application/x-mswrite',
    'wrl': 'model/vrml',
    'wsc': 'message/vnd.wfa.wsc',
    'wsdl': 'application/wsdl+xml',
    'wspolicy': 'application/wspolicy+xml',
    'wtb': 'application/vnd.webturbo',
    'wvx': 'video/x-ms-wvx',
    'x32': 'application/x-authorware-bin',
    'x3d': 'model/x3d+xml',
    'x3db': 'model/x3d+fastinfoset',
    'x3dbz': 'model/x3d+binary',
    'x3dv': 'model/x3d-vrml',
    'x3dvz': 'model/x3d+vrml',
    'x3dz': 'model/x3d+xml',
    'x_b': 'model/vnd.parasolid.transmit.binary',
    'x_t': 'model/vnd.parasolid.transmit.text',
    'xaml': 'application/xaml+xml',
    'xap': 'application/x-silverlight-app',
    'xar': 'application/vnd.xara',
    'xav': 'application/xcap-att+xml',
    'xbap': 'application/x-ms-xbap',
    'xbd': 'application/vnd.fujixerox.docuworks.binder',
    'xbm': 'image/x-xbitmap',
    'xca': 'application/xcap-caps+xml',
    'xcs': 'application/calendar+xml',
    'xdf': 'application/xcap-diff+xml',
    'xdm': 'application/vnd.syncml.dm+xml',
    'xdp': 'application/vnd.adobe.xdp+xml',
    'xdssc': 'application/dssc+xml',
    'xdw': 'application/vnd.fujixerox.docuworks',
    'xel': 'application/xcap-el+xml',
    'xenc': 'application/xenc+xml',
    'xer': 'application/patch-ops-error+xml',
    'xfdf': 'application/xfdf',
    'xfdl': 'application/vnd.xfdl',
    'xht': 'application/xhtml+xml',
    'xhtm': 'application/vnd.pwg-xhtml-print+xml',
    'xhtml': 'application/xhtml+xml',
    'xhvml': 'application/xv+xml',
    'xif': 'image/vnd.xiff',
    'xla': 'application/vnd.ms-excel',
    'xlam': 'application/vnd.ms-excel.addin.macroenabled.12',
    'xlc': 'application/vnd.ms-excel',
    'xlf': 'application/xliff+xml',
    'xlm': 'application/vnd.ms-excel',
    'xls': 'application/vnd.ms-excel',
    'xlsb': 'application/vnd.ms-excel.sheet.binary.macroenabled.12',
    'xlsm': 'application/vnd.ms-excel.sheet.macroenabled.12',
    'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'xlt': 'application/vnd.ms-excel',
    'xltm': 'application/vnd.ms-excel.template.macroenabled.12',
    'xltx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
    'xlw': 'application/vnd.ms-excel',
    'xm': 'audio/xm',
    'xml': 'text/xml',
    'xns': 'application/xcap-ns+xml',
    'xo': 'application/vnd.olpc-sugar',
    'xop': 'application/xop+xml',
    'xpi': 'application/x-xpinstall',
    'xpl': 'application/xproc+xml',
    'xpm': 'image/x-xpixmap',
    'xpr': 'application/vnd.is-xpr',
    'xps': 'application/vnd.ms-xpsdocument',
    'xpw': 'application/vnd.intercon.formnet',
    'xpx': 'application/vnd.intercon.formnet',
    'xsd': 'application/xml',
    'xsf': 'application/prs.xsf+xml',
    'xsl': 'application/xslt+xml',
    'xslt': 'application/xslt+xml',
    'xsm': 'application/vnd.syncml+xml',
    'xspf': 'application/xspf+xml',
    'xul': 'application/vnd.mozilla.xul+xml',
    'xvm': 'application/xv+xml',
    'xvml': 'application/xv+xml',
    'xwd': 'image/x-xwindowdump',
    'xyz': 'chemical/x-xyz',
    'xz': 'application/x-xz',
    'yaml': 'text/yaml',
    'yang': 'application/yang',
    'yin': 'application/yin+xml',
    'yml': 'text/yaml',
    'ymp': 'text/x-suse-ymp',
    'z1': 'application/x-zmachine',
    'z2': 'application/x-zmachine',
    'z3': 'application/x-zmachine',
    'z4': 'application/x-zmachine',
    'z5': 'application/x-zmachine',
    'z6': 'application/x-zmachine',
    'z7': 'application/x-zmachine',
    'z8': 'application/x-zmachine',
    'zaz': 'application/vnd.zzazz.deck+xml',
    'zip': 'application/zip',
    'zir': 'application/vnd.zul',
    'zirz': 'application/vnd.zul',
    'zmm': 'application/vnd.handheld-entertainment+xml'
} as const

export type Mime = keyof typeof MIMES

export const MIMES_NAME: { [x in Mime]: string } = {
    'css': 'Stylesheet',
    'js': 'JavaScript File',
    'mp4': 'MP4 Video',
    'dpx': 'DPX',
    'dwd': 'DWD',
    'exp': 'EXP',
    'ez2': 'EZ2',
    'ez3': 'EZ3',
    'f': 'F',
    'fdt': 'FDT',
    'fits': 'FITS',
    'gdoc': 'Google Doc',
    'ged': 'GEDCOM',
    'geojson': 'GeoJSON',
    'gramps': 'Gramps',
    'gre': 'GRE',
    'gsheet': 'Google Sheet',
    'gslides': 'Google Slides',
    'gz': 'Gzip',
    'heic': 'HEIC Image',
    'heics': 'HEIC Sequence',
    'heif': 'HEIF Image',
    'heifs': 'HEIF Sequence',
    'hej2': 'HEJ2',
    'held': 'HELD',
    'hsj2': 'HSJ2',
    'htc': 'HTML Component',
    'igl': 'IGL',
    'igm': 'IGM',
    'jp2': 'JPEG 2000',
    'jpf': 'JPEG 2000',
    'jpg2': 'JPEG 2000',
    'jph': 'JPEG 2000',
    'jsonld': 'JSON-LD',
    'jt': 'JT',
    'ktx2': 'KTX2',
    'lasxml': 'LAS XML',
    'list': 'LIST',
    'litcoffee': 'Literate CoffeeScript',
    'lnk': 'Shortcut',
    'log': 'Log File',
    'lostxml': 'LOST XML',
    'lrf': 'LRF',
    'lrm': 'LRM',
    'ltf': 'LTF',
    'lua': 'Lua Script',
    'luac': 'Lua Compiled Script',
    'maei': 'MAEI',
    'mgz': 'MGZ',
    'mjs': 'JavaScript Module',
    'mkd': 'Markdown',
    'mml': 'MathML',
    'mp4s': 'MPEG-4 Stream',
    'mp4v': 'MPEG-4 Video',
    'mpf': 'MPF',
    'msh': 'MSH',
    'msix': 'MSIX',
    'msixbundle': 'MSIX Bundle',
    'mvt': 'MVT',
    'mxmf': 'MXMF',
    'nq': 'N-Quads',
    'nt': 'N-Triples',
    'nzb': 'NZB',
    'obgx': 'OBGX',
    'ogex': 'OGEX',
    'opus': 'Opus Audio',
    'osm': 'OSM',
    'ova': 'OVA',
    'ovf': 'OVF',
    'owl': 'OWL',
    'pac': 'PAC',
    'pages': 'Pages Document',
    'php': 'PHP Script',
    'pkpass': 'Passbook',
    'pm': 'Perl Module',
    'provx': 'PROVX',
    'pti': 'PTI',
    'pyo': 'Python Compiled',
    'pyox': 'Python Oxidized',
    'raml': 'RAML',
    'rapd': 'RAPD',
    'relo': 'RELO',
    'rpm': 'RPM Package',
    'rsat': 'RSAT',
    'rsheet': 'RSHEET',
    'run': 'RUN',
    'rusd': 'RUSD',
    'sea': 'SEA',
    'senmlx': 'SENMLX',
    'sensmlx': 'SENSMLX',
    'shex': 'SHEX',
    'shtml': 'Server Side Include HTML',
    'sieve': 'Sieve',
    'slim': 'Slim',
    'slm': 'Slim',
    'sls': 'SLS',
    'spdx': 'SPDX',
    'stpx': 'STPX',
    'stpxz': 'STPXZ',
    'stpz': 'STPZ',
    'styl': 'Stylus',
    'stylus': 'Stylus',
    'swidtag': 'SWID Tag',
    't38': 'T38',
    'tap': 'TAP',
    'td': 'TD',
    'trig': 'TriG',
    'ttml': 'TTML',
    'u3d': 'U3D',
    'u8dsn': 'U8DSN',
    'u8hdr': 'U8HDR',
    'u8mdn': 'U8MDN',
    'u8msg': 'U8MSG',
    'ubj': 'UBJ',
    'uo': 'UO',
    'usda': 'USDA',
    'uvz': 'UVZ',
    'vdi': 'VirtualBox Disk Image',
    'vds': 'VDS',
    'vhd': 'VHD',
    'vmdk': 'VMDK',
    'vtf': 'VTF',
    'vtt': 'WebVTT',
    'wgsl': 'WGSL',
    'wmz': 'WMZ',
    'x32': 'x32',
    'x_b': 'X_B',
    'x_t': 'X_T',
    'xav': 'XAV',
    'xel': 'XEL',
    'xhtm': 'XHTML',
    'xns': 'XNS',
    'xsd': 'XSD',
    'xsf': 'XSF',
    'ymp': 'YMP',
    'z1': 'Z1',
    'z2': 'Z2',
    'z3': 'Z3',
    'z4': 'Z4',
    'z5': 'Z5',
    'z6': 'Z6',
    'z7': 'Z7',
    'z8': 'Z8',
    '123': 'Lotus 1-2-3',
    '1km': '1000minds Decision Model',
    '3dml': '3DML Text',
    '3ds': '3DS Image',
    '3g2': '3GPP2 Video',
    '3gp': '3GPP Video',
    '3gpp': '3GPP Video',
    '3mf': '3MF Model',
    '7z': '7-Zip Archive',
    'aab': 'Authorware Binary',
    'aac': 'AAC Audio',
    'aam': 'Authorware Map',
    'aas': 'Authorware Segment',
    'abw': 'AbiWord Document',
    'ac': 'N-Gage AC',
    'acc': 'American Dynamics ACC',
    'ace': 'Ace Archive',
    'acu': 'AcuCobol',
    'acutc': 'AcuCorp',
    'adp': 'ADPCM Audio',
    'adts': 'ADTS AAC Audio',
    'aep': 'Audiograph',
    'afm': 'Type1 Font',
    'afp': 'AFP MODCA',
    'age': 'Age',
    'ahead': 'Ahead Space',
    'ai': 'PostScript File',
    'aif': 'AIFF Audio',
    'aifc': 'AIFF-C Audio',
    'aiff': 'AIFF Audio',
    'air': 'Adobe AIR',
    'ait': 'AIT',
    'ami': 'Amiga AMI',
    'aml': 'AutomationML',
    'amlx': 'AutomationML ZIP',
    'amr': 'AMR Audio',
    'apk': 'Android Package',
    'apng': 'APNG Image',
    'appcache': 'Cache Manifest',
    'appinstaller': 'App Installer',
    'application': 'Microsoft Application',
    'appx': 'App Package',
    'appxbundle': 'App Bundle',
    'apr': 'Lotus Approach',
    'arc': 'FreeArc Archive',
    'arj': 'ARJ Archive',
    'asc': 'PGP Signature',
    'asf': 'ASF Video',
    'asm': 'Assembly Source',
    'aso': 'Accpac Simply ASO',
    'asx': 'ASF Redirector',
    'atc': 'AcuCorp',
    'atom': 'Atom Feed',
    'atomcat': 'Atom Publishing Protocol',
    'atomdeleted': 'Atom Deleted Entry',
    'atomsvc': 'Atom Service',
    'atx': 'Antix Game',
    'au': 'AU Audio',
    'avci': 'AVCI Image',
    'avcs': 'AVCS Image',
    'avi': 'AVI Video',
    'avif': 'AVIF Image',
    'aw': 'Applixware',
    'azf': 'Airzip File Secure',
    'azs': 'Airzip File Secure',
    'azv': 'Airzip Accelerator',
    'azw': 'Amazon Kindle',
    'b16': 'PCO B16',
    'bat': 'Batch File',
    'bcpio': 'Binary CPIO Archive',
    'bdf': 'BDF Font',
    'bdm': 'SyncML DM+WBXML',
    'bdoc': 'BDOC',
    'bed': 'RealVNC',
    'bh2': 'Fujitsu Oasys',
    'bin': 'Binary File',
    'blb': 'Interactive Fiction',
    'blorb': 'Interactive Fiction',
    'bmi': 'BMI',
    'bmml': 'Balsamiq Mockups',
    'bmp': 'Bitmap Image',
    'book': 'FrameMaker',
    'box': 'Previewsystems Box',
    'boz': 'Bzip2 Compressed',
    'bpk': 'Binary File',
    'bsp': 'Valve Source Map',
    'btf': 'PRISMA BTF',
    'btif': 'PRISMA BTIF',
    'buffer': 'Buffer',
    'bz': 'Bzip Archive',
    'bz2': 'Bzip2 Archive',
    'c': 'C Source',
    'c11amc': 'ClueTrust CartoMobile',
    'c11amz': 'ClueTrust CartoMobile',
    'c4d': 'Clonk C4Group',
    'c4f': 'Clonk C4Group',
    'c4g': 'Clonk C4Group',
    'c4p': 'Clonk C4Group',
    'c4u': 'Clonk C4Group',
    'cab': 'Cabinet File',
    'caf': 'CAF Audio',
    'cap': 'PCAP',
    'car': 'Curl CAR',
    'cat': 'Microsoft PKI',
    'cb7': 'Comic Book Archive',
    'cba': 'Comic Book Archive',
    'cbr': 'Comic Book Archive',
    'cbt': 'Comic Book Archive',
    'cbz': 'Comic Book Archive',
    'cc': 'C++ Source',
    'cco': 'Cocoa',
    'cct': 'Adobe Director',
    'ccxml': 'CCXML',
    'cdbcmsg': 'Contact CMsg',
    'cdf': 'NetCDF',
    'cdfx': 'CDFX',
    'cdkey': 'MediaStation CDKey',
    'cdmia': 'CDMI Capability',
    'cdmic': 'CDMI Container',
    'cdmid': 'CDMI Domain',
    'cdmio': 'CDMI Object',
    'cdmiq': 'CDMI Queue',
    'cdx': 'ChemDraw',
    'cdxml': 'ChemDraw XML',
    'cdy': 'Cinderella',
    'cer': 'PKIX Cert',
    'cfs': 'CFS Compressed',
    'cgm': 'CGM Image',
    'chat': 'X-Chat',
    'chm': 'Microsoft HTML Help',
    'chrt': 'KDE KChart',
    'cif': 'CIF',
    'cii': 'ANSER Web',
    'cil': 'Microsoft Artgalry',
    'cjs': 'Node.js',
    'cla': 'Claymore',
    'class': 'Java Class',
    'cld': 'CLD Model',
    'clkk': 'Clicker Keyboard',
    'clkp': 'Clicker Palette',
    'clkt': 'Clicker Template',
    'clkw': 'Clicker Wordbank',
    'clkx': 'Clicker',
    'clp': 'Microsoft Clip',
    'cmc': 'CosmoCaller',
    'cmdf': 'Chemical CMDL',
    'cml': 'Chemical CML',
    'cmp': 'CustomMenu',
    'cmx': 'CMX Image',
    'cod': 'Blackberry COD',
    'coffee': 'CoffeeScript',
    'com': 'DOS Command',
    'conf': 'Plain Text',
    'cpio': 'CPIO Archive',
    'cpl': 'CPL',
    'cpp': 'C++ Source',
    'cpt': 'Mac CompactPro',
    'crd': 'Microsoft Cardfile',
    'crl': 'PKIX CRL',
    'crt': 'X.509 Cert',
    'crx': 'Chrome Extension',
    'cryptonote': 'CryptoNote',
    'csh': 'C Shell Script',
    'csl': 'Citation Styles',
    'csml': 'Chemical CSML',
    'csp': 'Commonspace',
    'cst': 'Adobe Director',
    'csv': 'Comma Separated Values',
    'cu': 'CU-SeeMe',
    'curl': 'Curl',
    'cwl': 'CWL',
    'cww': 'CWW',
    'cxt': 'Adobe Director',
    'cxx': 'C++ Source',
    'dae': 'COLLADA',
    'daf': 'Mobius DAF',
    'dart': 'Dart',
    'dataless': 'FDSN SEED',
    'davmount': 'DAVMount',
    'dbf': 'DBF',
    'dbk': 'DocBook XML',
    'dcr': 'Adobe Director',
    'dcurl': 'Curl DCURL',
    'dd2': 'OMA DD2',
    'ddd': 'Fujitsu Oasys',
    'ddf': 'SyncML DM DDF',
    'dds': 'Microsoft DDS',
    'deb': 'Debian Package',
    'def': 'Plain Text',
    'deploy': 'Binary File',
    'der': 'X.509 Cert',
    'dfac': 'DreamFactory',
    'dgc': 'DGC Archive',
    'dib': 'Bitmap Image',
    'dic': 'C Source',
    'dir': 'Adobe Director',
    'dis': 'Mobius DIS',
    'disposition-notification': 'Disposition Notification',
    'dist': 'Binary File',
    'distz': 'Binary File',
    'djv': 'DjVu Image',
    'djvu': 'DjVu Image',
    'dll': 'Dynamic Link Library',
    'dmg': 'Apple Disk Image',
    'dmp': 'PCAP',
    'dms': 'Binary File',
    'dna': 'Binary File',
    'doc': 'Microsoft Word Document',
    'docm': 'Microsoft Word Document',
    'docx': 'Microsoft Word Document',
    'dot': 'Microsoft Word Template',
    'dotm': 'Microsoft Word Template',
    'dotx': 'Microsoft Word Template',
    'dp': 'DP',
    'dpg': 'DPGraph',
    'dra': 'DRA Audio',
    'drle': 'Raw Image',
    'dsc': 'Dscaml',
    'dssc': 'DSSC',
    'dtb': 'DTBook',
    'dtd': 'DTD',
    'dts': 'DTS Audio',
    'dtshd': 'DTS-HD Audio',
    'dump': 'DUMP',
    'dvb': 'DVB File',
    'dvi': 'DVI File',
    'dwf': 'Design Web Format',
    'dwg': 'DWG Drawing',
    'dxf': 'DXF Drawing',
    'dxp': 'Dxp',
    'dxr': 'Adobe Director',
    'ear': 'EAR File',
    'ecelp4800': 'E-CELP Audio',
    'ecelp7470': 'E-CELP Audio',
    'ecelp9600': 'E-CELP Audio',
    'ecma': 'ECMA',
    'edm': 'Mobius EDM',
    'edx': 'EDX',
    'efif': 'EFIF',
    'ei6': 'EI6',
    'elc': 'Emacs',
    'emf': 'EMF Image',
    'eml': 'Email',
    'emma': 'EMMA',
    'emotionml': 'EmotionML',
    'emz': 'EMZ Image',
    'eol': 'EOL',
    'eot': 'Embedded OpenType',
    'eps': 'Encapsulated PostScript',
    'epub': 'EPUB',
    'es3': 'ES3',
    'esa': 'ESA',
    'esf': 'ESF',
    'et3': 'Et3',
    'etx': 'Setext',
    'eva': 'EVA',
    'evy': 'EVY',
    'exe': 'Executable File',
    'exi': 'Efficient XML',
    'exr': 'EXR Image',
    'ext': 'Ext',
    'ez': 'EZ',
    'f4v': 'F4V Video',
    'f77': 'Fortran Source',
    'f90': 'Fortran Source',
    'fbs': 'FastBid Sheet',
    'fcdt': 'Adobe FormFlow',
    'fcs': 'FCS',
    'fdf': 'Adobe Forms',
    'fe_launch': 'Launch',
    'fg5': 'FormGuard',
    'fgd': 'Formatted Text',
    'fh': 'FreeHand',
    'fh4': 'FreeHand',
    'fh5': 'FreeHand',
    'fh7': 'FreeHand',
    'fhc': 'FreeHand',
    'fig': 'XFig',
    'flac': 'FLAC Audio',
    'fli': 'FLI Animation',
    'flo': 'Flo',
    'flv': 'Flash Video',
    'flw': 'Flare',
    'flx': 'Flare',
    'fly': 'Flyer',
    'fm': 'FrameMaker',
    'fnc': 'FNC',
    'fo': 'XSL-FO',
    'for': 'Fortran Source',
    'fpx': 'FlashPix',
    'frame': 'FrameMaker',
    'fsc': 'Friendly Software',
    'fst': 'FAST',
    'ftc': 'FTC',
    'fti': 'FTI',
    'fvt': 'FVT',
    'fxp': 'Flash Source',
    'fxpl': 'Flash Source',
    'fzs': 'FZS',
    'g2w': 'Go2Webinar',
    'g3': 'Group 3 Fax',
    'g3w': 'G3W',
    'gac': 'GAC',
    'gam': 'TADS',
    'gbr': 'Gerber',
    'gca': 'GCA',
    'gdl': 'GDL',
    'geo': 'GeoGebra',
    'gex': 'GeoGebra',
    'ggb': 'GeoGebra',
    'ggt': 'GeoGebra',
    'ghf': 'GHF',
    'gif': 'GIF Image',
    'gim': 'Gim',
    'glb': 'GLB Model',
    'gltf': 'GLTF Model',
    'gml': 'GML',
    'gmx': 'Gmx',
    'gnumeric': 'Gnumeric',
    'gph': 'GPH',
    'gpx': 'GPX',
    'gqf': 'GQF',
    'gqs': 'GQS',
    'gram': 'Grammars',
    'grv': 'Groove',
    'grxml': 'Grammars',
    'gsf': 'Ghostscript Font',
    'gtar': 'GNU Tar',
    'gtm': 'GTm',
    'gtw': 'GTW',
    'gv': 'Graphviz',
    'gxf': 'GXF',
    'gxt': 'GXT',
    'h': 'C Header',
    'h261': 'H.261',
    'h263': 'H.263',
    'h264': 'H.264',
    'hal': 'HAL',
    'hbci': 'Homebanking',
    'hbs': 'Handlebars',
    'hdd': 'HDD',
    'hdf': 'HDF',
    'hh': 'C++ Header',
    'hjson': 'HJSON',
    'hlp': 'Help File',
    'hpgl': 'HPGL',
    'hpid': 'HPID',
    'hps': 'HPS',
    'hqx': 'Macintosh BinHex',
    'htke': 'HTKE',
    'htm': 'HTML Document',
    'html': 'HTML Document',
    'hvd': 'HVD',
    'hvp': 'HVP',
    'hvs': 'HVS',
    'i2g': 'i2G',
    'icc': 'ICC Profile',
    'ice': 'ICE',
    'icm': 'ICM',
    'ico': 'Icon',
    'ics': 'iCalendar',
    'ief': 'IEF',
    'ifb': 'iCalendar',
    'ifm': 'IFM',
    'iges': 'IGES',
    'igs': 'IGES',
    'igx': 'iGrafx',
    'iif': 'IIF',
    'img': 'IMG',
    'imp': 'IMP',
    'ims': 'IMS',
    'in': 'Source',
    'ini': 'INI',
    'ink': 'InkML',
    'inkml': 'InkML',
    'install': 'Install',
    'iota': 'IOTA',
    'ipfix': 'IPFIX',
    'ipk': 'IPK',
    'irm': 'IRIS',
    'irp': 'IRP',
    'iso': 'ISO Disk Image',
    'itp': 'ITP',
    'its': 'ITS',
    'ivp': 'IVP',
    'ivu': 'IVU',
    'jad': 'JAD',
    'jade': 'Jade',
    'jam': 'JAM',
    'jar': 'Java Archive',
    'jardiff': 'JAR Diff',
    'java': 'Java Source',
    'jhc': 'JHC',
    'jisp': 'Jisp',
    'jls': 'JLS',
    'jlt': 'JLT',
    'jng': 'JNG',
    'jnlp': 'Java Web Start',
    'joda': 'Joda',
    'jpe': 'JPEG Image',
    'jpeg': 'JPEG Image',
    'jpg': 'JPEG Image',
    'jpgm': 'JPGM',
    'jpgv': 'JPGV',
    'jpm': 'JPM',
    'jpx': 'JPX',
    'json': 'JSON File',
    'json5': 'JSON5 File',
    'jsonml': 'JSON-ML File',
    'jsx': 'JSX',
    'jxr': 'JXR',
    'jxra': 'JXRA',
    'jxrs': 'JXRS',
    'jxs': 'JXS',
    'jxsc': 'JXSC',
    'jxsi': 'JXSI',
    'jxss': 'JXSS',
    'kar': 'KAR',
    'karbon': 'Karbon',
    'kdbx': 'KeePass Database',
    'key': 'Keynote',
    'kfo': 'KFO',
    'kia': 'KIA',
    'kml': 'KML',
    'kmz': 'KMZ',
    'kne': 'Kneeboard',
    'knp': 'Kneeboard',
    'kon': 'Kon',
    'kpr': 'KPresenter',
    'kpt': 'KPresenter',
    'kpxx': 'Karaoke',
    'ksp': 'KSpread',
    'ktr': 'Krita',
    'ktx': 'KTX',
    'ktz': 'Kahootz',
    'kwd': 'KWord',
    'kwt': 'KWord',
    'latex': 'LaTeX',
    'lbd': 'LBD',
    'lbe': 'LBE',
    'les': 'LES',
    'less': 'LESS',
    'lgr': 'LGR',
    'lha': 'LHA',
    'link66': 'Link66',
    'list3820': 'List3820',
    'listafp': 'ListAFP',
    'lvp': 'LVP',
    'lwp': 'LWP',
    'lzh': 'LZH',
    'm13': 'M13',
    'm14': 'M14',
    'm1v': 'MPEG Video',
    'm21': 'MPEG-21',
    'm2a': 'MPEG Audio',
    'm2v': 'MPEG Video',
    'm3a': 'MPEG Audio',
    'm3u': 'M3U Playlist',
    'm3u8': 'M3U8 Playlist',
    'm4a': 'MPEG-4 Audio',
    'm4p': 'MPEG-4 Audio',
    'm4s': 'MPEG-4 Segment',
    'm4u': 'M4U Playlist',
    'm4v': 'MPEG-4 Video',
    'ma': 'MATLAB',
    'mads': 'MADS',
    'mag': 'MAG',
    'maker': 'Maker',
    'man': 'Man Page',
    'manifest': 'Web App Manifest',
    'map': 'MAP',
    'mar': 'Mozilla Archive',
    'markdown': 'Markdown',
    'mathml': 'MathML',
    'mb': 'Mathematica',
    'mbk': 'Mobius MBK',
    'mbox': 'Mbox',
    'mc1': 'Media Control',
    'mcd': 'MCD',
    'mcurl': 'Curl Manifest',
    'md': 'Markdown',
    'mdb': 'Microsoft Access',
    'mdi': 'Microsoft Document Imaging',
    'mdx': 'Binary File',
    'me': 'Troff',
    'mesh': 'Mesh',
    'meta4': 'Meta4',
    'metalink': 'Metalink',
    'mets': 'METS',
    'mfm': 'MFM',
    'mft': 'MFT',
    'mgp': 'Magicpoint',
    'mid': 'MIDI Audio',
    'midi': 'MIDI Audio',
    'mie': 'MIE',
    'mif': 'FrameMaker',
    'mime': 'MIME',
    'mj2': 'Motion JPEG 2000',
    'mjp2': 'Motion JPEG 2000',
    'mk3d': 'Matroska 3D',
    'mka': 'Matroska Audio',
    'mks': 'Matroska Subtitles',
    'mkv': 'Matroska Video',
    'mlp': 'MLP Audio',
    'mmd': 'Cocoa Project',
    'mmf': 'MMF',
    'mmr': 'Fax Image',
    'mng': 'MNG Video',
    'mny': 'Microsoft Money',
    'mobi': 'Mobipocket',
    'mods': 'MODS',
    'mov': 'QuickTime Video',
    'movie': 'Movie',
    'mp2': 'MPEG Audio',
    'mp21': 'MPEG-21',
    'mp2a': 'MPEG Audio',
    'mp3': 'MP3 Audio',
    'mp4a': 'MPEG-4 Audio',
    'mpc': 'MPC Audio',
    'mpd': 'MPEG-DASH',
    'mpe': 'MPEG Video',
    'mpeg': 'MPEG Video',
    'mpg': 'MPEG Video',
    'mpg4': 'MPEG-4 Video',
    'mpga': 'MPEG Audio',
    'mpkg': 'Apple Installer Package',
    'mpm': 'MPM',
    'mpn': 'MPN',
    'mpp': 'Microsoft Project',
    'mpt': 'Microsoft Project',
    'mpy': 'MPY',
    'mqy': 'MQY',
    'mrc': 'MARC',
    'mrcx': 'MARCXML',
    'ms': 'Troff',
    'mscml': 'MSCML',
    'mseed': 'MiniSEED',
    'mseq': '3GPP MSEQ',
    'msf': 'MSF',
    'msg': 'Outlook Message',
    'msi': 'Microsoft Installer',
    'msl': 'MSL',
    'msm': 'MSM',
    'msp': 'MSP',
    'msty': 'Muzy',
    'mtl': 'OBJ MTL',
    'mts': 'MPEG Transport Stream',
    'mus': 'Mus',
    'musd': 'MUSD',
    'musicxml': 'MusicXML',
    'mvb': 'Multimedia Viewer',
    'mwf': 'Multimedia WorkFlow',
    'mxf': 'Material Exchange Format',
    'mxl': 'MusicXML',
    'mxml': 'MXML',
    'mxs': 'MXS',
    'mxu': 'MPEG URL',
    'n-gage': 'N-Gage Game',
    'n3': 'N3',
    'nb': 'Mathematica',
    'nbp': 'Mathematica',
    'nc': 'NetCDF',
    'ncx': 'NCX',
    'nfo': 'NFO',
    'ngdat': 'NGDAT',
    'nitf': 'NITF',
    'nlu': 'NLU',
    'nml': 'NML',
    'nnd': 'NND',
    'nns': 'NNS',
    'nnw': 'NNW',
    'npx': 'NPX',
    'nsc': 'NSC',
    'nsf': 'NSF',
    'ntf': 'NITF',
    'numbers': 'Numbers',
    'oa2': 'OpenDoc',
    'oa3': 'OpenDoc',
    'oas': 'OAS',
    'obd': 'OBD',
    'obj': 'OBJ',
    'oda': 'ODA',
    'odb': 'LibreOffice Database',
    'odc': 'LibreOffice Calc',
    'odf': 'LibreOffice Formula',
    'odft': 'LibreOffice Formula Template',
    'odg': 'LibreOffice Draw',
    'odi': 'LibreOffice Image',
    'odm': 'LibreOffice Text Master',
    'odp': 'LibreOffice Presentation',
    'ods': 'LibreOffice Spreadsheet',
    'odt': 'LibreOffice Text',
    'oga': 'OGG Audio',
    'ogg': 'OGG',
    'ogv': 'OGG Video',
    'ogx': 'OGG Multiplexed',
    'omdoc': 'OMDoc',
    'onepkg': 'Microsoft OneNote',
    'onetmp': 'Microsoft OneNote',
    'onetoc': 'Microsoft OneNote',
    'onetoc2': 'Microsoft OneNote',
    'opf': 'Open Packaging Format',
    'opml': 'OPML',
    'oprc': 'Palm',
    'org': 'Org',
    'osf': 'OSF',
    'osfpvg': 'OSFPVG',
    'otc': 'LibreOffice Calc Template',
    'otf': 'OpenType Font',
    'otg': 'LibreOffice Draw Template',
    'oth': 'LibreOffice Text Web',
    'oti': 'LibreOffice Image Template',
    'otp': 'LibreOffice Impress Template',
    'ots': 'LibreOffice Spreadsheet Template',
    'ott': 'LibreOffice Text Template',
    'oxps': 'OpenXPS',
    'oxt': 'LibreOffice Extension',
    'p': 'Pascal',
    'p10': 'PKCS #10',
    'p12': 'PKCS #12',
    'p7b': 'PKCS #7',
    'p7c': 'PKCS #7',
    'p7m': 'PKCS #7',
    'p7r': 'PKCS #7',
    'p7s': 'PKCS #7',
    'p8': 'PKCS #8',
    'pas': 'Pascal',
    'paw': 'PAW',
    'pbd': 'PBD',
    'pbm': 'Portable Bitmap',
    'pcap': 'PCAP',
    'pcf': 'PCF',
    'pcl': 'PCL',
    'pclxl': 'PCL XL',
    'pct': 'PICT Image',
    'pcurl': 'Curl',
    'pcx': 'PCX Image',
    'pdb': 'Palm',
    'pde': 'Processing',
    'pdf': 'PDF',
    'pem': 'PEM',
    'pfa': 'PostScript Font',
    'pfb': 'PostScript Font',
    'pfm': 'Adobe PFM',
    'pfr': 'PFR',
    'pfx': 'PKCS #12',
    'pgm': 'Portable Graymap',
    'pgn': 'PGN',
    'pgp': 'PGP',
    'pic': 'PICT Image',
    'pkg': 'Package',
    'pki': 'PKI',
    'pkipath': 'PKI Path',
    'pl': 'Perl',
    'plb': 'PLB',
    'plc': 'PLT',
    'plf': 'PLF',
    'pls': 'PLS',
    'pml': 'PML',
    'png': 'PNG Image',
    'pnm': 'Portable Any Map',
    'portpkg': 'PORTPKG',
    'pot': 'PowerPoint Template',
    'potm': 'PowerPoint Template',
    'potx': 'PowerPoint Template',
    'ppam': 'PowerPoint Add-in',
    'ppd': 'PPD',
    'ppm': 'Portable Pixmap',
    'pps': 'PowerPoint Slide Show',
    'ppsm': 'PowerPoint Slide Show',
    'ppsx': 'PowerPoint Slide Show',
    'ppt': 'PowerPoint Presentation',
    'pptm': 'PowerPoint Presentation',
    'pptx': 'PowerPoint Presentation',
    'pqa': 'PQA',
    'prc': 'Palm',
    'pre': 'PRE',
    'prf': 'PRF',
    'ps': 'PostScript',
    'psb': 'Photoshop Big',
    'psd': 'Photoshop',
    'psf': 'Adobe PSF',
    'pskcxml': 'PSKC',
    'ptid': 'PTID',
    'pub': 'Microsoft Publisher',
    'pvb': 'PVB',
    'pwn': 'PWN',
    'pya': 'PYR Audio',
    'pyv': 'PYV Video',
    'qam': 'QAM',
    'qbo': 'QuickBooks',
    'qfx': 'Quicken',
    'qps': 'QPS',
    'qt': 'QuickTime Video',
    'qwd': 'QuarkXPress',
    'qwt': 'QuarkXPress',
    'qxb': 'QuarkXPress',
    'qxd': 'QuarkXPress',
    'qxl': 'QuarkXPress',
    'qxt': 'QuarkXPress',
    'ra': 'RealAudio',
    'ram': 'RealAudio',
    'rar': 'RAR Archive',
    'ras': 'Sun Raster',
    'rcprofile': 'IRobot',
    'rdf': 'RDF',
    'rdz': 'RemoteDocs',
    'rep': 'Business Objects',
    'res': 'Resource File',
    'rgb': 'RGB Bitmap',
    'rif': 'RIFF',
    'rip': "Hit'n'Mix",
    'ris': 'RIS',
    'rl': 'Resource Locator',
    'rlc': 'RLC',
    'rld': 'RLD',
    'rm': 'RealMedia',
    'rmi': 'RMID',
    'rmp': 'RealMedia',
    'rms': 'RealMedia',
    'rmvb': 'RealMedia Variable Bitrate',
    'rnc': 'RNC',
    'rng': 'RELAX NG',
    'roa': 'ROA',
    'roff': 'Troff',
    'rp9': 'RP9',
    'rpss': 'RPSS',
    'rpst': 'RPST',
    'rq': 'SPARQL',
    'rs': 'Rust Source',
    'rsd': 'RSD',
    'rss': 'RSS',
    'rtf': 'Rich Text',
    'rtx': 'Rich Text',
    's': 'Assembly Source',
    's3m': 'S3M',
    'saf': 'SAF',
    'sass': 'SASS',
    'sbml': 'SBML',
    'sc': 'Script',
    'scd': 'SCD',
    'scm': 'Scheme',
    'scq': 'SCQ',
    'scs': 'SCS',
    'scss': 'SCSS',
    'scurl': 'CURL Source',
    'sda': 'StarOffice Draw',
    'sdc': 'StarOffice Calc',
    'sdd': 'StarOffice Impress',
    'sdkd': 'SDKD',
    'sdkm': 'SDKM',
    'sdp': 'SDP',
    'sdw': 'StarOffice Writer',
    'see': 'SEE',
    'seed': 'SEED',
    'sema': 'Sema',
    'semd': 'Sema',
    'semf': 'Sema',
    'ser': 'SER',
    'setpay': 'SET Payment',
    'setreg': 'SET Registration',
    'sfd-hdstx': 'SFD',
    'sfs': 'SFS',
    'sfv': 'SFV',
    'sgi': 'SGI Image',
    'sgl': 'SGL',
    'sgm': 'SGML',
    'sgml': 'SGML',
    'sh': 'Shell Script',
    'shar': 'Shell Archive',
    'shf': 'Shf',
    'sid': 'Digital Sound',
    'sig': 'PGP',
    'sil': 'SIL',
    'silo': 'Silo',
    'sis': 'SIS',
    'sisx': 'SISX',
    'sit': 'StuffIt',
    'sitx': 'StuffIt',
    'siv': 'SIV',
    'skd': 'SKD',
    'skm': 'SKM',
    'skp': 'SketchUp',
    'skt': 'SKT',
    'sldm': 'PowerPoint Slide Show',
    'sldx': 'PowerPoint Slide Show',
    'slt': 'SE',
    'sm': 'SM',
    'smf': 'SMF',
    'smi': 'SAMI',
    'smil': 'SMIL',
    'smv': 'SMV',
    'smzip': 'StepMania',
    'snd': 'SND',
    'snf': 'SNF',
    'so': 'Shared Library',
    'spc': 'SPC',
    'spf': 'SPF',
    'spl': 'FutureSplash',
    'spot': 'Spot',
    'spp': 'SPP',
    'spq': 'SPQ',
    'spx': 'Speex Audio',
    'sql': 'SQL',
    'src': 'Source',
    'srt': 'SubRip',
    'sru': 'SRU',
    'srx': 'SRX',
    'ssdl': 'SSDL',
    'sse': 'SSE',
    'ssf': 'SSF',
    'ssml': 'SSML',
    'st': 'Squeak Source',
    'stc': 'OpenOffice.org Calc',
    'std': 'OpenOffice.org Draw',
    'stf': 'World',
    'sti': 'OpenOffice.org Impress',
    'stk': 'HyperStudio',
    'stl': 'STL',
    'str': 'PGP',
    'stw': 'OpenOffice.org Writer',
    'sub': 'SubViewer',
    'sus': 'SUS',
    'susp': 'SUS',
    'sv4cpio': 'SV4CPIO',
    'sv4crc': 'SV4CRC',
    'svc': 'SVC',
    'svd': 'SVD',
    'svg': 'SVG Image',
    'svgz': 'SVG Image',
    'swa': 'Shockwave',
    'swf': 'Flash',
    'swi': 'Swig',
    'sxc': 'OpenOffice.org Calc',
    'sxd': 'OpenOffice.org Draw',
    'sxg': 'OpenOffice.org Writer',
    'sxi': 'OpenOffice.org Impress',
    'sxm': 'OpenOffice.org Math',
    'sxw': 'OpenOffice.org Writer',
    't': 'Troff',
    't3': 'TADS',
    'taglet': 'Taglet',
    'tao': 'TAO',
    'tar': 'Tar',
    'tcap': 'TCap',
    'tcl': 'Tcl Script',
    'teacher': 'Teacher',
    'tei': 'TEI',
    'teicorpus': 'TEI',
    'tex': 'TeX',
    'texi': 'Texinfo',
    'texinfo': 'Texinfo',
    'text': 'Text',
    'tfi': 'TFI',
    'tfm': 'TeX TFM',
    'tfx': 'TFX',
    'tga': 'TGA Image',
    'thmx': 'Theme',
    'tif': 'TIFF Image',
    'tiff': 'TIFF Image',
    'tk': 'Tcl Script',
    'tmo': 'TMO',
    'toml': 'TOML',
    'torrent': 'BitTorrent',
    'tpl': 'TPL',
    'tpt': 'TPT',
    'tr': 'Troff',
    'tra': 'TRA',
    'trm': 'TRM',
    'ts': 'MPEG Transport Stream',
    'tsd': 'TSD',
    'tsv': 'TSV',
    'ttc': 'TrueType Font Collection',
    'ttf': 'TrueType Font',
    'ttl': 'TTL',
    'twd': 'TWD',
    'twds': 'TWDS',
    'txd': 'TXD',
    'txf': 'TXF',
    'txt': 'Text',
    'u32': 'U32',
    'udeb': 'UDEB',
    'ufd': 'UFD',
    'ufdl': 'UFDL',
    'ulx': 'ULX',
    'umj': 'UMJ',
    'unityweb': 'Unity Web',
    'uoml': 'UOML',
    'uri': 'URI',
    'uris': 'URI',
    'urls': 'URL',
    'usdz': 'USDZ',
    'ustar': 'Ustar',
    'utz': 'UTZ',
    'uu': 'UUEncode',
    'uva': 'UVA',
    'uvd': 'UVD',
    'uvf': 'UVF',
    'uvg': 'UVG',
    'uvh': 'UVH',
    'uvi': 'UVI',
    'uvm': 'UVM',
    'uvp': 'UVP',
    'uvs': 'UVS',
    'uvt': 'UVT',
    'uvu': 'UVU',
    'uvv': 'UVV',
    'uvva': 'UVVA',
    'uvvd': 'UVVD',
    'uvvf': 'UVVF',
    'uvvg': 'UVVG',
    'uvvh': 'UVVH',
    'uvvi': 'UVVI',
    'uvvm': 'UVVM',
    'uvvp': 'UVVP',
    'uvvs': 'UVVS',
    'uvvt': 'UVVT',
    'uvvu': 'UVVU',
    'uvvv': 'UVVV',
    'uvvx': 'UVVX',
    'uvvz': 'UVVZ',
    'uvx': 'UVX',
    'vbox': 'VirtualBox',
    'vbox-extpack': 'VirtualBox Extension Pack',
    'vcard': 'VCard',
    'vcd': 'VCD',
    'vcf': 'VCard',
    'vcg': 'VCG',
    'vcs': 'vCalendar',
    'vcx': 'VCX',
    'vis': 'VIS',
    'viv': 'Vivo',
    'vob': 'DVD Video',
    'vor': 'StarOffice Template',
    'vox': 'Vox',
    'vrml': 'VRML',
    'vsd': 'Visio',
    'vsf': 'VSF',
    'vss': 'Visio',
    'vst': 'Visio',
    'vsw': 'Visio',
    'vtu': 'VTU',
    'vxml': 'VoiceXML',
    'w3d': 'W3D',
    'wad': 'WAD',
    'wadl': 'WADL',
    'war': 'Web Archive',
    'wasm': 'WebAssembly',
    'wav': 'WAV Audio',
    'wax': 'Windows Media Audio',
    'wbmp': 'WAP Bitmap',
    'wbs': 'WBS',
    'wbxml': 'WAP Binary XML',
    'wcm': 'WCM',
    'wdb': 'WDB',
    'wdp': 'WDP',
    'weba': 'WEBM Audio',
    'webapp': 'Web App Manifest',
    'webm': 'WEBM Video',
    'webmanifest': 'Web App Manifest',
    'webp': 'WEBP Image',
    'wg': 'WG',
    'wgt': 'WGT',
    'wif': 'WIF',
    'wks': 'WKS',
    'wm': 'Windows Media Video',
    'wma': 'Windows Media Audio',
    'wmd': 'Windows Media Video',
    'wmf': 'WMF',
    'wml': 'WML',
    'wmlc': 'WMLC',
    'wmls': 'WMLScript',
    'wmlsc': 'WMLScript',
    'wmv': 'Windows Media Video',
    'wmx': 'Windows Media Video',
    'woff': 'Web Open Font Format',
    'woff2': 'Web Open Font Format',
    'wpd': 'WordPerfect',
    'wpl': 'Windows Media Video',
    'wps': 'WPS',
    'wqd': 'WQD',
    'wri': 'Microsoft Write',
    'wrl': 'VRML',
    'wsc': 'WSC',
    'wsdl': 'WSDL',
    'wspolicy': 'Web Services Policy',
    'wtb': 'WTB',
    'wvx': 'Windows Media Video',
    'x3d': 'X3D',
    'x3db': 'X3D',
    'x3dbz': 'X3D',
    'x3dv': 'X3D',
    'x3dvz': 'X3D',
    'x3dz': 'X3D',
    'xaml': 'XAML',
    'xap': 'XAP',
    'xar': 'XAR',
    'xbap': 'XBAP',
    'xbd': 'XBD',
    'xbm': 'XBM',
    'xca': 'XCA',
    'xcs': 'XCS',
    'xdf': 'XDF',
    'xdm': 'XDM',
    'xdp': 'XDP',
    'xdssc': 'XDSSC',
    'xdw': 'XDW',
    'xenc': 'XENC',
    'xer': 'XER',
    'xfdf': 'XFDF',
    'xfdl': 'XFDL',
    'xht': 'XHTML',
    'xhtml': 'XHTML',
    'xhvml': 'XHVML',
    'xif': 'XIFF',
    'xla': 'Excel Add-In',
    'xlam': 'Excel Add-In',
    'xlc': 'Excel Chart',
    'xlf': 'XLIFF',
    'xlm': 'Excel Macro',
    'xls': 'Excel Spreadsheet',
    'xlsb': 'Excel Binary',
    'xlsm': 'Excel Spreadsheet',
    'xlsx': 'Excel Spreadsheet',
    'xlt': 'Excel Template',
    'xltm': 'Excel Template',
    'xltx': 'Excel Template',
    'xlw': 'Excel Workspace',
    'xm': 'XM',
    'xml': 'XML',
    'xo': 'XO',
    'xop': 'XOP',
    'xpi': 'XPI',
    'xpl': 'XPL',
    'xpm': 'XPM',
    'xpr': 'XPR',
    'xps': 'XPS',
    'xpw': 'XPW',
    'xpx': 'XPX',
    'xsl': 'XSL',
    'xslt': 'XSLT',
    'xsm': 'XSM',
    'xspf': 'XSPF',
    'xul': 'XUL',
    'xvm': 'XVM',
    'xvml': 'XVML',
    'xwd': 'XWD',
    'xyz': 'XYZ',
    'xz': 'XZ',
    'yaml': 'YAML',
    'yang': 'YANG',
    'yin': 'YIN',
    'yml': 'YAML',
    'zaz': 'ZAZ',
    'zip': 'ZIP Archive',
    'zir': 'ZIR',
    'zirz': 'ZIR',
    'zmm': 'ZMM',
}


export const MIMES_EXTENSION = Object.keys(MIMES).reduce((acc, mime) => ({ ...acc, [mime]: mime }), {}) as { [x in Mime]: x }
